// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_INCLUDED_message_2eproto
#define PROTOBUF_INCLUDED_message_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_message_2eproto 

namespace protobuf_message_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_message_2eproto
class InformationalMessageContents;
class InformationalMessageContentsDefaultTypeInternal;
extern InformationalMessageContentsDefaultTypeInternal _InformationalMessageContents_default_instance_;
class InformationalMessageContents_CollectionInformationRecord;
class InformationalMessageContents_CollectionInformationRecordDefaultTypeInternal;
extern InformationalMessageContents_CollectionInformationRecordDefaultTypeInternal _InformationalMessageContents_CollectionInformationRecord_default_instance_;
class InformationalMessageContents_CollectionInformationRecord_CreationRateData;
class InformationalMessageContents_CollectionInformationRecord_CreationRateDataDefaultTypeInternal;
extern InformationalMessageContents_CollectionInformationRecord_CreationRateDataDefaultTypeInternal _InformationalMessageContents_CollectionInformationRecord_CreationRateData_default_instance_;
class KeyspaceMessageContents;
class KeyspaceMessageContentsDefaultTypeInternal;
extern KeyspaceMessageContentsDefaultTypeInternal _KeyspaceMessageContents_default_instance_;
class KeyspaceMessageContents_Keyspace;
class KeyspaceMessageContents_KeyspaceDefaultTypeInternal;
extern KeyspaceMessageContents_KeyspaceDefaultTypeInternal _KeyspaceMessageContents_Keyspace_default_instance_;
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
namespace google {
namespace protobuf {
template<> ::InformationalMessageContents* Arena::CreateMaybeMessage<::InformationalMessageContents>(Arena*);
template<> ::InformationalMessageContents_CollectionInformationRecord* Arena::CreateMaybeMessage<::InformationalMessageContents_CollectionInformationRecord>(Arena*);
template<> ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* Arena::CreateMaybeMessage<::InformationalMessageContents_CollectionInformationRecord_CreationRateData>(Arena*);
template<> ::KeyspaceMessageContents* Arena::CreateMaybeMessage<::KeyspaceMessageContents>(Arena*);
template<> ::KeyspaceMessageContents_Keyspace* Arena::CreateMaybeMessage<::KeyspaceMessageContents_Keyspace>(Arena*);
template<> ::Message* Arena::CreateMaybeMessage<::Message>(Arena*);
}  // namespace protobuf
}  // namespace google

enum Message_ChannelState {
  Message_ChannelState_INITIAL_STARTUP = 0,
  Message_ChannelState_NORMAL_COMMUNICATION = 1,
  Message_ChannelState_CHANNEL_SHUTDOWN = 2,
  Message_ChannelState_Message_ChannelState_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Message_ChannelState_Message_ChannelState_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Message_ChannelState_IsValid(int value);
const Message_ChannelState Message_ChannelState_ChannelState_MIN = Message_ChannelState_INITIAL_STARTUP;
const Message_ChannelState Message_ChannelState_ChannelState_MAX = Message_ChannelState_CHANNEL_SHUTDOWN;
const int Message_ChannelState_ChannelState_ARRAYSIZE = Message_ChannelState_ChannelState_MAX + 1;

const ::google::protobuf::EnumDescriptor* Message_ChannelState_descriptor();
inline const ::std::string& Message_ChannelState_Name(Message_ChannelState value) {
  return ::google::protobuf::internal::NameOfEnum(
    Message_ChannelState_descriptor(), value);
}
inline bool Message_ChannelState_Parse(
    const ::std::string& name, Message_ChannelState* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Message_ChannelState>(
    Message_ChannelState_descriptor(), name, value);
}
enum Message_MessageType {
  Message_MessageType_INFORMATION = 0,
  Message_MessageType_KEYSPACE = 1,
  Message_MessageType_DATA_REPLICATION_UNUSED = 2,
  Message_MessageType_Message_MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Message_MessageType_Message_MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Message_MessageType_IsValid(int value);
const Message_MessageType Message_MessageType_MessageType_MIN = Message_MessageType_INFORMATION;
const Message_MessageType Message_MessageType_MessageType_MAX = Message_MessageType_DATA_REPLICATION_UNUSED;
const int Message_MessageType_MessageType_ARRAYSIZE = Message_MessageType_MessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* Message_MessageType_descriptor();
inline const ::std::string& Message_MessageType_Name(Message_MessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    Message_MessageType_descriptor(), value);
}
inline bool Message_MessageType_Parse(
    const ::std::string& name, Message_MessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Message_MessageType>(
    Message_MessageType_descriptor(), name, value);
}
// ===================================================================

class InformationalMessageContents_CollectionInformationRecord_CreationRateData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:InformationalMessageContents.CollectionInformationRecord.CreationRateData) */ {
 public:
  InformationalMessageContents_CollectionInformationRecord_CreationRateData();
  virtual ~InformationalMessageContents_CollectionInformationRecord_CreationRateData();

  InformationalMessageContents_CollectionInformationRecord_CreationRateData(const InformationalMessageContents_CollectionInformationRecord_CreationRateData& from);

  inline InformationalMessageContents_CollectionInformationRecord_CreationRateData& operator=(const InformationalMessageContents_CollectionInformationRecord_CreationRateData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InformationalMessageContents_CollectionInformationRecord_CreationRateData(InformationalMessageContents_CollectionInformationRecord_CreationRateData&& from) noexcept
    : InformationalMessageContents_CollectionInformationRecord_CreationRateData() {
    *this = ::std::move(from);
  }

  inline InformationalMessageContents_CollectionInformationRecord_CreationRateData& operator=(InformationalMessageContents_CollectionInformationRecord_CreationRateData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const InformationalMessageContents_CollectionInformationRecord_CreationRateData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InformationalMessageContents_CollectionInformationRecord_CreationRateData* internal_default_instance() {
    return reinterpret_cast<const InformationalMessageContents_CollectionInformationRecord_CreationRateData*>(
               &_InformationalMessageContents_CollectionInformationRecord_CreationRateData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(InformationalMessageContents_CollectionInformationRecord_CreationRateData* other);
  friend void swap(InformationalMessageContents_CollectionInformationRecord_CreationRateData& a, InformationalMessageContents_CollectionInformationRecord_CreationRateData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InformationalMessageContents_CollectionInformationRecord_CreationRateData* New() const final {
    return CreateMaybeMessage<InformationalMessageContents_CollectionInformationRecord_CreationRateData>(NULL);
  }

  InformationalMessageContents_CollectionInformationRecord_CreationRateData* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InformationalMessageContents_CollectionInformationRecord_CreationRateData>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InformationalMessageContents_CollectionInformationRecord_CreationRateData& from);
  void MergeFrom(const InformationalMessageContents_CollectionInformationRecord_CreationRateData& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InformationalMessageContents_CollectionInformationRecord_CreationRateData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double shortAllocationRatio = 1;
  void clear_shortallocationratio();
  static const int kShortAllocationRatioFieldNumber = 1;
  double shortallocationratio() const;
  void set_shortallocationratio(double value);

  // double longAllocationRatio = 2;
  void clear_longallocationratio();
  static const int kLongAllocationRatioFieldNumber = 2;
  double longallocationratio() const;
  void set_longallocationratio(double value);

  // double createdPreviousDay = 3;
  void clear_createdpreviousday();
  static const int kCreatedPreviousDayFieldNumber = 3;
  double createdpreviousday() const;
  void set_createdpreviousday(double value);

  // double createdPreviousWeek = 4;
  void clear_createdpreviousweek();
  static const int kCreatedPreviousWeekFieldNumber = 4;
  double createdpreviousweek() const;
  void set_createdpreviousweek(double value);

  // @@protoc_insertion_point(class_scope:InformationalMessageContents.CollectionInformationRecord.CreationRateData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double shortallocationratio_;
  double longallocationratio_;
  double createdpreviousday_;
  double createdpreviousweek_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class InformationalMessageContents_CollectionInformationRecord : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:InformationalMessageContents.CollectionInformationRecord) */ {
 public:
  InformationalMessageContents_CollectionInformationRecord();
  virtual ~InformationalMessageContents_CollectionInformationRecord();

  InformationalMessageContents_CollectionInformationRecord(const InformationalMessageContents_CollectionInformationRecord& from);

  inline InformationalMessageContents_CollectionInformationRecord& operator=(const InformationalMessageContents_CollectionInformationRecord& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InformationalMessageContents_CollectionInformationRecord(InformationalMessageContents_CollectionInformationRecord&& from) noexcept
    : InformationalMessageContents_CollectionInformationRecord() {
    *this = ::std::move(from);
  }

  inline InformationalMessageContents_CollectionInformationRecord& operator=(InformationalMessageContents_CollectionInformationRecord&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const InformationalMessageContents_CollectionInformationRecord& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InformationalMessageContents_CollectionInformationRecord* internal_default_instance() {
    return reinterpret_cast<const InformationalMessageContents_CollectionInformationRecord*>(
               &_InformationalMessageContents_CollectionInformationRecord_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(InformationalMessageContents_CollectionInformationRecord* other);
  friend void swap(InformationalMessageContents_CollectionInformationRecord& a, InformationalMessageContents_CollectionInformationRecord& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InformationalMessageContents_CollectionInformationRecord* New() const final {
    return CreateMaybeMessage<InformationalMessageContents_CollectionInformationRecord>(NULL);
  }

  InformationalMessageContents_CollectionInformationRecord* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InformationalMessageContents_CollectionInformationRecord>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InformationalMessageContents_CollectionInformationRecord& from);
  void MergeFrom(const InformationalMessageContents_CollectionInformationRecord& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InformationalMessageContents_CollectionInformationRecord* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef InformationalMessageContents_CollectionInformationRecord_CreationRateData CreationRateData;

  // accessors -------------------------------------------------------

  // string collectionName = 1;
  void clear_collectionname();
  static const int kCollectionNameFieldNumber = 1;
  const ::std::string& collectionname() const;
  void set_collectionname(const ::std::string& value);
  #if LANG_CXX11
  void set_collectionname(::std::string&& value);
  #endif
  void set_collectionname(const char* value);
  void set_collectionname(const char* value, size_t size);
  ::std::string* mutable_collectionname();
  ::std::string* release_collectionname();
  void set_allocated_collectionname(::std::string* collectionname);

  // .InformationalMessageContents.CollectionInformationRecord.CreationRateData creationRateData = 2;
  bool has_creationratedata() const;
  void clear_creationratedata();
  static const int kCreationRateDataFieldNumber = 2;
  private:
  const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData& _internal_creationratedata() const;
  public:
  const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData& creationratedata() const;
  ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* release_creationratedata();
  ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* mutable_creationratedata();
  void set_allocated_creationratedata(::InformationalMessageContents_CollectionInformationRecord_CreationRateData* creationratedata);

  // @@protoc_insertion_point(class_scope:InformationalMessageContents.CollectionInformationRecord)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr collectionname_;
  ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* creationratedata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class InformationalMessageContents : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:InformationalMessageContents) */ {
 public:
  InformationalMessageContents();
  virtual ~InformationalMessageContents();

  InformationalMessageContents(const InformationalMessageContents& from);

  inline InformationalMessageContents& operator=(const InformationalMessageContents& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InformationalMessageContents(InformationalMessageContents&& from) noexcept
    : InformationalMessageContents() {
    *this = ::std::move(from);
  }

  inline InformationalMessageContents& operator=(InformationalMessageContents&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const InformationalMessageContents& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InformationalMessageContents* internal_default_instance() {
    return reinterpret_cast<const InformationalMessageContents*>(
               &_InformationalMessageContents_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(InformationalMessageContents* other);
  friend void swap(InformationalMessageContents& a, InformationalMessageContents& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InformationalMessageContents* New() const final {
    return CreateMaybeMessage<InformationalMessageContents>(NULL);
  }

  InformationalMessageContents* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InformationalMessageContents>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InformationalMessageContents& from);
  void MergeFrom(const InformationalMessageContents& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InformationalMessageContents* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef InformationalMessageContents_CollectionInformationRecord CollectionInformationRecord;

  // accessors -------------------------------------------------------

  // repeated .InformationalMessageContents.CollectionInformationRecord records = 1;
  int records_size() const;
  void clear_records();
  static const int kRecordsFieldNumber = 1;
  ::InformationalMessageContents_CollectionInformationRecord* mutable_records(int index);
  ::google::protobuf::RepeatedPtrField< ::InformationalMessageContents_CollectionInformationRecord >*
      mutable_records();
  const ::InformationalMessageContents_CollectionInformationRecord& records(int index) const;
  ::InformationalMessageContents_CollectionInformationRecord* add_records();
  const ::google::protobuf::RepeatedPtrField< ::InformationalMessageContents_CollectionInformationRecord >&
      records() const;

  // @@protoc_insertion_point(class_scope:InformationalMessageContents)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::InformationalMessageContents_CollectionInformationRecord > records_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class KeyspaceMessageContents_Keyspace : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:KeyspaceMessageContents.Keyspace) */ {
 public:
  KeyspaceMessageContents_Keyspace();
  virtual ~KeyspaceMessageContents_Keyspace();

  KeyspaceMessageContents_Keyspace(const KeyspaceMessageContents_Keyspace& from);

  inline KeyspaceMessageContents_Keyspace& operator=(const KeyspaceMessageContents_Keyspace& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  KeyspaceMessageContents_Keyspace(KeyspaceMessageContents_Keyspace&& from) noexcept
    : KeyspaceMessageContents_Keyspace() {
    *this = ::std::move(from);
  }

  inline KeyspaceMessageContents_Keyspace& operator=(KeyspaceMessageContents_Keyspace&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const KeyspaceMessageContents_Keyspace& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const KeyspaceMessageContents_Keyspace* internal_default_instance() {
    return reinterpret_cast<const KeyspaceMessageContents_Keyspace*>(
               &_KeyspaceMessageContents_Keyspace_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(KeyspaceMessageContents_Keyspace* other);
  friend void swap(KeyspaceMessageContents_Keyspace& a, KeyspaceMessageContents_Keyspace& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline KeyspaceMessageContents_Keyspace* New() const final {
    return CreateMaybeMessage<KeyspaceMessageContents_Keyspace>(NULL);
  }

  KeyspaceMessageContents_Keyspace* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<KeyspaceMessageContents_Keyspace>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const KeyspaceMessageContents_Keyspace& from);
  void MergeFrom(const KeyspaceMessageContents_Keyspace& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KeyspaceMessageContents_Keyspace* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // uint64 startID = 2;
  void clear_startid();
  static const int kStartIDFieldNumber = 2;
  ::google::protobuf::uint64 startid() const;
  void set_startid(::google::protobuf::uint64 value);

  // uint64 endID = 3;
  void clear_endid();
  static const int kEndIDFieldNumber = 3;
  ::google::protobuf::uint64 endid() const;
  void set_endid(::google::protobuf::uint64 value);

  // uint32 suffixBits = 4;
  void clear_suffixbits();
  static const int kSuffixBitsFieldNumber = 4;
  ::google::protobuf::uint32 suffixbits() const;
  void set_suffixbits(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:KeyspaceMessageContents.Keyspace)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint64 startid_;
  ::google::protobuf::uint64 endid_;
  ::google::protobuf::uint32 suffixbits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class KeyspaceMessageContents : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:KeyspaceMessageContents) */ {
 public:
  KeyspaceMessageContents();
  virtual ~KeyspaceMessageContents();

  KeyspaceMessageContents(const KeyspaceMessageContents& from);

  inline KeyspaceMessageContents& operator=(const KeyspaceMessageContents& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  KeyspaceMessageContents(KeyspaceMessageContents&& from) noexcept
    : KeyspaceMessageContents() {
    *this = ::std::move(from);
  }

  inline KeyspaceMessageContents& operator=(KeyspaceMessageContents&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const KeyspaceMessageContents& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const KeyspaceMessageContents* internal_default_instance() {
    return reinterpret_cast<const KeyspaceMessageContents*>(
               &_KeyspaceMessageContents_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(KeyspaceMessageContents* other);
  friend void swap(KeyspaceMessageContents& a, KeyspaceMessageContents& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline KeyspaceMessageContents* New() const final {
    return CreateMaybeMessage<KeyspaceMessageContents>(NULL);
  }

  KeyspaceMessageContents* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<KeyspaceMessageContents>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const KeyspaceMessageContents& from);
  void MergeFrom(const KeyspaceMessageContents& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KeyspaceMessageContents* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef KeyspaceMessageContents_Keyspace Keyspace;

  // accessors -------------------------------------------------------

  // repeated .KeyspaceMessageContents.Keyspace keyspaces = 1;
  int keyspaces_size() const;
  void clear_keyspaces();
  static const int kKeyspacesFieldNumber = 1;
  ::KeyspaceMessageContents_Keyspace* mutable_keyspaces(int index);
  ::google::protobuf::RepeatedPtrField< ::KeyspaceMessageContents_Keyspace >*
      mutable_keyspaces();
  const ::KeyspaceMessageContents_Keyspace& keyspaces(int index) const;
  ::KeyspaceMessageContents_Keyspace* add_keyspaces();
  const ::google::protobuf::RepeatedPtrField< ::KeyspaceMessageContents_Keyspace >&
      keyspaces() const;

  // @@protoc_insertion_point(class_scope:KeyspaceMessageContents)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::KeyspaceMessageContents_Keyspace > keyspaces_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(Message&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  enum MessageCase {
    kInfo = 8,
    kKeyspace = 9,
    MESSAGE_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(Message* other);
  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Message* New() const final {
    return CreateMaybeMessage<Message>(NULL);
  }

  Message* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Message_ChannelState ChannelState;
  static const ChannelState INITIAL_STARTUP =
    Message_ChannelState_INITIAL_STARTUP;
  static const ChannelState NORMAL_COMMUNICATION =
    Message_ChannelState_NORMAL_COMMUNICATION;
  static const ChannelState CHANNEL_SHUTDOWN =
    Message_ChannelState_CHANNEL_SHUTDOWN;
  static inline bool ChannelState_IsValid(int value) {
    return Message_ChannelState_IsValid(value);
  }
  static const ChannelState ChannelState_MIN =
    Message_ChannelState_ChannelState_MIN;
  static const ChannelState ChannelState_MAX =
    Message_ChannelState_ChannelState_MAX;
  static const int ChannelState_ARRAYSIZE =
    Message_ChannelState_ChannelState_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ChannelState_descriptor() {
    return Message_ChannelState_descriptor();
  }
  static inline const ::std::string& ChannelState_Name(ChannelState value) {
    return Message_ChannelState_Name(value);
  }
  static inline bool ChannelState_Parse(const ::std::string& name,
      ChannelState* value) {
    return Message_ChannelState_Parse(name, value);
  }

  typedef Message_MessageType MessageType;
  static const MessageType INFORMATION =
    Message_MessageType_INFORMATION;
  static const MessageType KEYSPACE =
    Message_MessageType_KEYSPACE;
  static const MessageType DATA_REPLICATION_UNUSED =
    Message_MessageType_DATA_REPLICATION_UNUSED;
  static inline bool MessageType_IsValid(int value) {
    return Message_MessageType_IsValid(value);
  }
  static const MessageType MessageType_MIN =
    Message_MessageType_MessageType_MIN;
  static const MessageType MessageType_MAX =
    Message_MessageType_MessageType_MAX;
  static const int MessageType_ARRAYSIZE =
    Message_MessageType_MessageType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  MessageType_descriptor() {
    return Message_MessageType_descriptor();
  }
  static inline const ::std::string& MessageType_Name(MessageType value) {
    return Message_MessageType_Name(value);
  }
  static inline bool MessageType_Parse(const ::std::string& name,
      MessageType* value) {
    return Message_MessageType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // bytes sourceNodeID = 1;
  void clear_sourcenodeid();
  static const int kSourceNodeIDFieldNumber = 1;
  const ::std::string& sourcenodeid() const;
  void set_sourcenodeid(const ::std::string& value);
  #if LANG_CXX11
  void set_sourcenodeid(::std::string&& value);
  #endif
  void set_sourcenodeid(const char* value);
  void set_sourcenodeid(const void* value, size_t size);
  ::std::string* mutable_sourcenodeid();
  ::std::string* release_sourcenodeid();
  void set_allocated_sourcenodeid(::std::string* sourcenodeid);

  // bytes destNodeID = 2;
  void clear_destnodeid();
  static const int kDestNodeIDFieldNumber = 2;
  const ::std::string& destnodeid() const;
  void set_destnodeid(const ::std::string& value);
  #if LANG_CXX11
  void set_destnodeid(::std::string&& value);
  #endif
  void set_destnodeid(const char* value);
  void set_destnodeid(const void* value, size_t size);
  ::std::string* mutable_destnodeid();
  ::std::string* release_destnodeid();
  void set_allocated_destnodeid(::std::string* destnodeid);

  // .google.protobuf.Timestamp timestamp = 5;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 5;
  private:
  const ::google::protobuf::Timestamp& _internal_timestamp() const;
  public:
  const ::google::protobuf::Timestamp& timestamp() const;
  ::google::protobuf::Timestamp* release_timestamp();
  ::google::protobuf::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::google::protobuf::Timestamp* timestamp);

  // uint64 lastReceivedMsg = 3;
  void clear_lastreceivedmsg();
  static const int kLastReceivedMsgFieldNumber = 3;
  ::google::protobuf::uint64 lastreceivedmsg() const;
  void set_lastreceivedmsg(::google::protobuf::uint64 value);

  // .Message.ChannelState channelState = 4;
  void clear_channelstate();
  static const int kChannelStateFieldNumber = 4;
  ::Message_ChannelState channelstate() const;
  void set_channelstate(::Message_ChannelState value);

  // .Message.MessageType messageType = 7;
  void clear_messagetype();
  static const int kMessageTypeFieldNumber = 7;
  ::Message_MessageType messagetype() const;
  void set_messagetype(::Message_MessageType value);

  // sint64 messageID = 6;
  void clear_messageid();
  static const int kMessageIDFieldNumber = 6;
  ::google::protobuf::int64 messageid() const;
  void set_messageid(::google::protobuf::int64 value);

  // .InformationalMessageContents info = 8;
  bool has_info() const;
  void clear_info();
  static const int kInfoFieldNumber = 8;
  private:
  const ::InformationalMessageContents& _internal_info() const;
  public:
  const ::InformationalMessageContents& info() const;
  ::InformationalMessageContents* release_info();
  ::InformationalMessageContents* mutable_info();
  void set_allocated_info(::InformationalMessageContents* info);

  // .KeyspaceMessageContents keyspace = 9;
  bool has_keyspace() const;
  void clear_keyspace();
  static const int kKeyspaceFieldNumber = 9;
  private:
  const ::KeyspaceMessageContents& _internal_keyspace() const;
  public:
  const ::KeyspaceMessageContents& keyspace() const;
  ::KeyspaceMessageContents* release_keyspace();
  ::KeyspaceMessageContents* mutable_keyspace();
  void set_allocated_keyspace(::KeyspaceMessageContents* keyspace);

  void clear_message();
  MessageCase message_case() const;
  // @@protoc_insertion_point(class_scope:Message)
 private:
  void set_has_info();
  void set_has_keyspace();

  inline bool has_message() const;
  inline void clear_has_message();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr sourcenodeid_;
  ::google::protobuf::internal::ArenaStringPtr destnodeid_;
  ::google::protobuf::Timestamp* timestamp_;
  ::google::protobuf::uint64 lastreceivedmsg_;
  int channelstate_;
  int messagetype_;
  ::google::protobuf::int64 messageid_;
  union MessageUnion {
    MessageUnion() {}
    ::InformationalMessageContents* info_;
    ::KeyspaceMessageContents* keyspace_;
  } message_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::protobuf_message_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InformationalMessageContents_CollectionInformationRecord_CreationRateData

// double shortAllocationRatio = 1;
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::clear_shortallocationratio() {
  shortallocationratio_ = 0;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::shortallocationratio() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.CreationRateData.shortAllocationRatio)
  return shortallocationratio_;
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::set_shortallocationratio(double value) {
  
  shortallocationratio_ = value;
  // @@protoc_insertion_point(field_set:InformationalMessageContents.CollectionInformationRecord.CreationRateData.shortAllocationRatio)
}

// double longAllocationRatio = 2;
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::clear_longallocationratio() {
  longallocationratio_ = 0;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::longallocationratio() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.CreationRateData.longAllocationRatio)
  return longallocationratio_;
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::set_longallocationratio(double value) {
  
  longallocationratio_ = value;
  // @@protoc_insertion_point(field_set:InformationalMessageContents.CollectionInformationRecord.CreationRateData.longAllocationRatio)
}

// double createdPreviousDay = 3;
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::clear_createdpreviousday() {
  createdpreviousday_ = 0;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::createdpreviousday() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.CreationRateData.createdPreviousDay)
  return createdpreviousday_;
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::set_createdpreviousday(double value) {
  
  createdpreviousday_ = value;
  // @@protoc_insertion_point(field_set:InformationalMessageContents.CollectionInformationRecord.CreationRateData.createdPreviousDay)
}

// double createdPreviousWeek = 4;
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::clear_createdpreviousweek() {
  createdpreviousweek_ = 0;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::createdpreviousweek() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.CreationRateData.createdPreviousWeek)
  return createdpreviousweek_;
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::set_createdpreviousweek(double value) {
  
  createdpreviousweek_ = value;
  // @@protoc_insertion_point(field_set:InformationalMessageContents.CollectionInformationRecord.CreationRateData.createdPreviousWeek)
}

// -------------------------------------------------------------------

// InformationalMessageContents_CollectionInformationRecord

// string collectionName = 1;
inline void InformationalMessageContents_CollectionInformationRecord::clear_collectionname() {
  collectionname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& InformationalMessageContents_CollectionInformationRecord::collectionname() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.collectionName)
  return collectionname_.GetNoArena();
}
inline void InformationalMessageContents_CollectionInformationRecord::set_collectionname(const ::std::string& value) {
  
  collectionname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:InformationalMessageContents.CollectionInformationRecord.collectionName)
}
#if LANG_CXX11
inline void InformationalMessageContents_CollectionInformationRecord::set_collectionname(::std::string&& value) {
  
  collectionname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:InformationalMessageContents.CollectionInformationRecord.collectionName)
}
#endif
inline void InformationalMessageContents_CollectionInformationRecord::set_collectionname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  collectionname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:InformationalMessageContents.CollectionInformationRecord.collectionName)
}
inline void InformationalMessageContents_CollectionInformationRecord::set_collectionname(const char* value, size_t size) {
  
  collectionname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:InformationalMessageContents.CollectionInformationRecord.collectionName)
}
inline ::std::string* InformationalMessageContents_CollectionInformationRecord::mutable_collectionname() {
  
  // @@protoc_insertion_point(field_mutable:InformationalMessageContents.CollectionInformationRecord.collectionName)
  return collectionname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* InformationalMessageContents_CollectionInformationRecord::release_collectionname() {
  // @@protoc_insertion_point(field_release:InformationalMessageContents.CollectionInformationRecord.collectionName)
  
  return collectionname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InformationalMessageContents_CollectionInformationRecord::set_allocated_collectionname(::std::string* collectionname) {
  if (collectionname != NULL) {
    
  } else {
    
  }
  collectionname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), collectionname);
  // @@protoc_insertion_point(field_set_allocated:InformationalMessageContents.CollectionInformationRecord.collectionName)
}

// .InformationalMessageContents.CollectionInformationRecord.CreationRateData creationRateData = 2;
inline bool InformationalMessageContents_CollectionInformationRecord::has_creationratedata() const {
  return this != internal_default_instance() && creationratedata_ != NULL;
}
inline void InformationalMessageContents_CollectionInformationRecord::clear_creationratedata() {
  if (GetArenaNoVirtual() == NULL && creationratedata_ != NULL) {
    delete creationratedata_;
  }
  creationratedata_ = NULL;
}
inline const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData& InformationalMessageContents_CollectionInformationRecord::_internal_creationratedata() const {
  return *creationratedata_;
}
inline const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData& InformationalMessageContents_CollectionInformationRecord::creationratedata() const {
  const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* p = creationratedata_;
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.creationRateData)
  return p != NULL ? *p : *reinterpret_cast<const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData*>(
      &::_InformationalMessageContents_CollectionInformationRecord_CreationRateData_default_instance_);
}
inline ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* InformationalMessageContents_CollectionInformationRecord::release_creationratedata() {
  // @@protoc_insertion_point(field_release:InformationalMessageContents.CollectionInformationRecord.creationRateData)
  
  ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* temp = creationratedata_;
  creationratedata_ = NULL;
  return temp;
}
inline ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* InformationalMessageContents_CollectionInformationRecord::mutable_creationratedata() {
  
  if (creationratedata_ == NULL) {
    auto* p = CreateMaybeMessage<::InformationalMessageContents_CollectionInformationRecord_CreationRateData>(GetArenaNoVirtual());
    creationratedata_ = p;
  }
  // @@protoc_insertion_point(field_mutable:InformationalMessageContents.CollectionInformationRecord.creationRateData)
  return creationratedata_;
}
inline void InformationalMessageContents_CollectionInformationRecord::set_allocated_creationratedata(::InformationalMessageContents_CollectionInformationRecord_CreationRateData* creationratedata) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete creationratedata_;
  }
  if (creationratedata) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      creationratedata = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, creationratedata, submessage_arena);
    }
    
  } else {
    
  }
  creationratedata_ = creationratedata;
  // @@protoc_insertion_point(field_set_allocated:InformationalMessageContents.CollectionInformationRecord.creationRateData)
}

// -------------------------------------------------------------------

// InformationalMessageContents

// repeated .InformationalMessageContents.CollectionInformationRecord records = 1;
inline int InformationalMessageContents::records_size() const {
  return records_.size();
}
inline void InformationalMessageContents::clear_records() {
  records_.Clear();
}
inline ::InformationalMessageContents_CollectionInformationRecord* InformationalMessageContents::mutable_records(int index) {
  // @@protoc_insertion_point(field_mutable:InformationalMessageContents.records)
  return records_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::InformationalMessageContents_CollectionInformationRecord >*
InformationalMessageContents::mutable_records() {
  // @@protoc_insertion_point(field_mutable_list:InformationalMessageContents.records)
  return &records_;
}
inline const ::InformationalMessageContents_CollectionInformationRecord& InformationalMessageContents::records(int index) const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.records)
  return records_.Get(index);
}
inline ::InformationalMessageContents_CollectionInformationRecord* InformationalMessageContents::add_records() {
  // @@protoc_insertion_point(field_add:InformationalMessageContents.records)
  return records_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::InformationalMessageContents_CollectionInformationRecord >&
InformationalMessageContents::records() const {
  // @@protoc_insertion_point(field_list:InformationalMessageContents.records)
  return records_;
}

// -------------------------------------------------------------------

// KeyspaceMessageContents_Keyspace

// string name = 1;
inline void KeyspaceMessageContents_Keyspace::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& KeyspaceMessageContents_Keyspace::name() const {
  // @@protoc_insertion_point(field_get:KeyspaceMessageContents.Keyspace.name)
  return name_.GetNoArena();
}
inline void KeyspaceMessageContents_Keyspace::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:KeyspaceMessageContents.Keyspace.name)
}
#if LANG_CXX11
inline void KeyspaceMessageContents_Keyspace::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:KeyspaceMessageContents.Keyspace.name)
}
#endif
inline void KeyspaceMessageContents_Keyspace::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:KeyspaceMessageContents.Keyspace.name)
}
inline void KeyspaceMessageContents_Keyspace::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:KeyspaceMessageContents.Keyspace.name)
}
inline ::std::string* KeyspaceMessageContents_Keyspace::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:KeyspaceMessageContents.Keyspace.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* KeyspaceMessageContents_Keyspace::release_name() {
  // @@protoc_insertion_point(field_release:KeyspaceMessageContents.Keyspace.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KeyspaceMessageContents_Keyspace::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:KeyspaceMessageContents.Keyspace.name)
}

// uint64 startID = 2;
inline void KeyspaceMessageContents_Keyspace::clear_startid() {
  startid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 KeyspaceMessageContents_Keyspace::startid() const {
  // @@protoc_insertion_point(field_get:KeyspaceMessageContents.Keyspace.startID)
  return startid_;
}
inline void KeyspaceMessageContents_Keyspace::set_startid(::google::protobuf::uint64 value) {
  
  startid_ = value;
  // @@protoc_insertion_point(field_set:KeyspaceMessageContents.Keyspace.startID)
}

// uint64 endID = 3;
inline void KeyspaceMessageContents_Keyspace::clear_endid() {
  endid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 KeyspaceMessageContents_Keyspace::endid() const {
  // @@protoc_insertion_point(field_get:KeyspaceMessageContents.Keyspace.endID)
  return endid_;
}
inline void KeyspaceMessageContents_Keyspace::set_endid(::google::protobuf::uint64 value) {
  
  endid_ = value;
  // @@protoc_insertion_point(field_set:KeyspaceMessageContents.Keyspace.endID)
}

// uint32 suffixBits = 4;
inline void KeyspaceMessageContents_Keyspace::clear_suffixbits() {
  suffixbits_ = 0u;
}
inline ::google::protobuf::uint32 KeyspaceMessageContents_Keyspace::suffixbits() const {
  // @@protoc_insertion_point(field_get:KeyspaceMessageContents.Keyspace.suffixBits)
  return suffixbits_;
}
inline void KeyspaceMessageContents_Keyspace::set_suffixbits(::google::protobuf::uint32 value) {
  
  suffixbits_ = value;
  // @@protoc_insertion_point(field_set:KeyspaceMessageContents.Keyspace.suffixBits)
}

// -------------------------------------------------------------------

// KeyspaceMessageContents

// repeated .KeyspaceMessageContents.Keyspace keyspaces = 1;
inline int KeyspaceMessageContents::keyspaces_size() const {
  return keyspaces_.size();
}
inline void KeyspaceMessageContents::clear_keyspaces() {
  keyspaces_.Clear();
}
inline ::KeyspaceMessageContents_Keyspace* KeyspaceMessageContents::mutable_keyspaces(int index) {
  // @@protoc_insertion_point(field_mutable:KeyspaceMessageContents.keyspaces)
  return keyspaces_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::KeyspaceMessageContents_Keyspace >*
KeyspaceMessageContents::mutable_keyspaces() {
  // @@protoc_insertion_point(field_mutable_list:KeyspaceMessageContents.keyspaces)
  return &keyspaces_;
}
inline const ::KeyspaceMessageContents_Keyspace& KeyspaceMessageContents::keyspaces(int index) const {
  // @@protoc_insertion_point(field_get:KeyspaceMessageContents.keyspaces)
  return keyspaces_.Get(index);
}
inline ::KeyspaceMessageContents_Keyspace* KeyspaceMessageContents::add_keyspaces() {
  // @@protoc_insertion_point(field_add:KeyspaceMessageContents.keyspaces)
  return keyspaces_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::KeyspaceMessageContents_Keyspace >&
KeyspaceMessageContents::keyspaces() const {
  // @@protoc_insertion_point(field_list:KeyspaceMessageContents.keyspaces)
  return keyspaces_;
}

// -------------------------------------------------------------------

// Message

// bytes sourceNodeID = 1;
inline void Message::clear_sourcenodeid() {
  sourcenodeid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Message::sourcenodeid() const {
  // @@protoc_insertion_point(field_get:Message.sourceNodeID)
  return sourcenodeid_.GetNoArena();
}
inline void Message::set_sourcenodeid(const ::std::string& value) {
  
  sourcenodeid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Message.sourceNodeID)
}
#if LANG_CXX11
inline void Message::set_sourcenodeid(::std::string&& value) {
  
  sourcenodeid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.sourceNodeID)
}
#endif
inline void Message::set_sourcenodeid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  sourcenodeid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.sourceNodeID)
}
inline void Message::set_sourcenodeid(const void* value, size_t size) {
  
  sourcenodeid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.sourceNodeID)
}
inline ::std::string* Message::mutable_sourcenodeid() {
  
  // @@protoc_insertion_point(field_mutable:Message.sourceNodeID)
  return sourcenodeid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message::release_sourcenodeid() {
  // @@protoc_insertion_point(field_release:Message.sourceNodeID)
  
  return sourcenodeid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_sourcenodeid(::std::string* sourcenodeid) {
  if (sourcenodeid != NULL) {
    
  } else {
    
  }
  sourcenodeid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sourcenodeid);
  // @@protoc_insertion_point(field_set_allocated:Message.sourceNodeID)
}

// bytes destNodeID = 2;
inline void Message::clear_destnodeid() {
  destnodeid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Message::destnodeid() const {
  // @@protoc_insertion_point(field_get:Message.destNodeID)
  return destnodeid_.GetNoArena();
}
inline void Message::set_destnodeid(const ::std::string& value) {
  
  destnodeid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Message.destNodeID)
}
#if LANG_CXX11
inline void Message::set_destnodeid(::std::string&& value) {
  
  destnodeid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.destNodeID)
}
#endif
inline void Message::set_destnodeid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  destnodeid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.destNodeID)
}
inline void Message::set_destnodeid(const void* value, size_t size) {
  
  destnodeid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.destNodeID)
}
inline ::std::string* Message::mutable_destnodeid() {
  
  // @@protoc_insertion_point(field_mutable:Message.destNodeID)
  return destnodeid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message::release_destnodeid() {
  // @@protoc_insertion_point(field_release:Message.destNodeID)
  
  return destnodeid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_destnodeid(::std::string* destnodeid) {
  if (destnodeid != NULL) {
    
  } else {
    
  }
  destnodeid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), destnodeid);
  // @@protoc_insertion_point(field_set_allocated:Message.destNodeID)
}

// uint64 lastReceivedMsg = 3;
inline void Message::clear_lastreceivedmsg() {
  lastreceivedmsg_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Message::lastreceivedmsg() const {
  // @@protoc_insertion_point(field_get:Message.lastReceivedMsg)
  return lastreceivedmsg_;
}
inline void Message::set_lastreceivedmsg(::google::protobuf::uint64 value) {
  
  lastreceivedmsg_ = value;
  // @@protoc_insertion_point(field_set:Message.lastReceivedMsg)
}

// .Message.ChannelState channelState = 4;
inline void Message::clear_channelstate() {
  channelstate_ = 0;
}
inline ::Message_ChannelState Message::channelstate() const {
  // @@protoc_insertion_point(field_get:Message.channelState)
  return static_cast< ::Message_ChannelState >(channelstate_);
}
inline void Message::set_channelstate(::Message_ChannelState value) {
  
  channelstate_ = value;
  // @@protoc_insertion_point(field_set:Message.channelState)
}

// .google.protobuf.Timestamp timestamp = 5;
inline bool Message::has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != NULL;
}
inline const ::google::protobuf::Timestamp& Message::_internal_timestamp() const {
  return *timestamp_;
}
inline const ::google::protobuf::Timestamp& Message::timestamp() const {
  const ::google::protobuf::Timestamp* p = timestamp_;
  // @@protoc_insertion_point(field_get:Message.timestamp)
  return p != NULL ? *p : *reinterpret_cast<const ::google::protobuf::Timestamp*>(
      &::google::protobuf::_Timestamp_default_instance_);
}
inline ::google::protobuf::Timestamp* Message::release_timestamp() {
  // @@protoc_insertion_point(field_release:Message.timestamp)
  
  ::google::protobuf::Timestamp* temp = timestamp_;
  timestamp_ = NULL;
  return temp;
}
inline ::google::protobuf::Timestamp* Message::mutable_timestamp() {
  
  if (timestamp_ == NULL) {
    auto* p = CreateMaybeMessage<::google::protobuf::Timestamp>(GetArenaNoVirtual());
    timestamp_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Message.timestamp)
  return timestamp_;
}
inline void Message::set_allocated_timestamp(::google::protobuf::Timestamp* timestamp) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:Message.timestamp)
}

// sint64 messageID = 6;
inline void Message::clear_messageid() {
  messageid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Message::messageid() const {
  // @@protoc_insertion_point(field_get:Message.messageID)
  return messageid_;
}
inline void Message::set_messageid(::google::protobuf::int64 value) {
  
  messageid_ = value;
  // @@protoc_insertion_point(field_set:Message.messageID)
}

// .Message.MessageType messageType = 7;
inline void Message::clear_messagetype() {
  messagetype_ = 0;
}
inline ::Message_MessageType Message::messagetype() const {
  // @@protoc_insertion_point(field_get:Message.messageType)
  return static_cast< ::Message_MessageType >(messagetype_);
}
inline void Message::set_messagetype(::Message_MessageType value) {
  
  messagetype_ = value;
  // @@protoc_insertion_point(field_set:Message.messageType)
}

// .InformationalMessageContents info = 8;
inline bool Message::has_info() const {
  return message_case() == kInfo;
}
inline void Message::set_has_info() {
  _oneof_case_[0] = kInfo;
}
inline void Message::clear_info() {
  if (has_info()) {
    delete message_.info_;
    clear_has_message();
  }
}
inline const ::InformationalMessageContents& Message::_internal_info() const {
  return *message_.info_;
}
inline ::InformationalMessageContents* Message::release_info() {
  // @@protoc_insertion_point(field_release:Message.info)
  if (has_info()) {
    clear_has_message();
      ::InformationalMessageContents* temp = message_.info_;
    message_.info_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::InformationalMessageContents& Message::info() const {
  // @@protoc_insertion_point(field_get:Message.info)
  return has_info()
      ? *message_.info_
      : *reinterpret_cast< ::InformationalMessageContents*>(&::_InformationalMessageContents_default_instance_);
}
inline ::InformationalMessageContents* Message::mutable_info() {
  if (!has_info()) {
    clear_message();
    set_has_info();
    message_.info_ = CreateMaybeMessage< ::InformationalMessageContents >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:Message.info)
  return message_.info_;
}

// .KeyspaceMessageContents keyspace = 9;
inline bool Message::has_keyspace() const {
  return message_case() == kKeyspace;
}
inline void Message::set_has_keyspace() {
  _oneof_case_[0] = kKeyspace;
}
inline void Message::clear_keyspace() {
  if (has_keyspace()) {
    delete message_.keyspace_;
    clear_has_message();
  }
}
inline const ::KeyspaceMessageContents& Message::_internal_keyspace() const {
  return *message_.keyspace_;
}
inline ::KeyspaceMessageContents* Message::release_keyspace() {
  // @@protoc_insertion_point(field_release:Message.keyspace)
  if (has_keyspace()) {
    clear_has_message();
      ::KeyspaceMessageContents* temp = message_.keyspace_;
    message_.keyspace_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::KeyspaceMessageContents& Message::keyspace() const {
  // @@protoc_insertion_point(field_get:Message.keyspace)
  return has_keyspace()
      ? *message_.keyspace_
      : *reinterpret_cast< ::KeyspaceMessageContents*>(&::_KeyspaceMessageContents_default_instance_);
}
inline ::KeyspaceMessageContents* Message::mutable_keyspace() {
  if (!has_keyspace()) {
    clear_message();
    set_has_keyspace();
    message_.keyspace_ = CreateMaybeMessage< ::KeyspaceMessageContents >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:Message.keyspace)
  return message_.keyspace_;
}

inline bool Message::has_message() const {
  return message_case() != MESSAGE_NOT_SET;
}
inline void Message::clear_has_message() {
  _oneof_case_[0] = MESSAGE_NOT_SET;
}
inline Message::MessageCase Message::message_case() const {
  return Message::MessageCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Message_ChannelState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Message_ChannelState>() {
  return ::Message_ChannelState_descriptor();
}
template <> struct is_proto_enum< ::Message_MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Message_MessageType>() {
  return ::Message_MessageType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_message_2eproto
