// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.


#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2eproto;
class InformationalMessageContents;
class InformationalMessageContentsDefaultTypeInternal;
extern InformationalMessageContentsDefaultTypeInternal _InformationalMessageContents_default_instance_;
class InformationalMessageContents_CollectionInformationRecord;
class InformationalMessageContents_CollectionInformationRecordDefaultTypeInternal;
extern InformationalMessageContents_CollectionInformationRecordDefaultTypeInternal _InformationalMessageContents_CollectionInformationRecord_default_instance_;
class InformationalMessageContents_CollectionInformationRecord_CreationRateData;
class InformationalMessageContents_CollectionInformationRecord_CreationRateDataDefaultTypeInternal;
extern InformationalMessageContents_CollectionInformationRecord_CreationRateDataDefaultTypeInternal _InformationalMessageContents_CollectionInformationRecord_CreationRateData_default_instance_;
class KeyspaceMessageContents;
class KeyspaceMessageContentsDefaultTypeInternal;
extern KeyspaceMessageContentsDefaultTypeInternal _KeyspaceMessageContents_default_instance_;
class KeyspaceMessageContents_Keyspace;
class KeyspaceMessageContents_KeyspaceDefaultTypeInternal;
extern KeyspaceMessageContents_KeyspaceDefaultTypeInternal _KeyspaceMessageContents_Keyspace_default_instance_;
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::InformationalMessageContents* Arena::CreateMaybeMessage<::InformationalMessageContents>(Arena*);
template<> ::InformationalMessageContents_CollectionInformationRecord* Arena::CreateMaybeMessage<::InformationalMessageContents_CollectionInformationRecord>(Arena*);
template<> ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* Arena::CreateMaybeMessage<::InformationalMessageContents_CollectionInformationRecord_CreationRateData>(Arena*);
template<> ::KeyspaceMessageContents* Arena::CreateMaybeMessage<::KeyspaceMessageContents>(Arena*);
template<> ::KeyspaceMessageContents_Keyspace* Arena::CreateMaybeMessage<::KeyspaceMessageContents_Keyspace>(Arena*);
template<> ::Message* Arena::CreateMaybeMessage<::Message>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum Message_ChannelState : int {
  Message_ChannelState_INITIAL_STARTUP = 0,
  Message_ChannelState_NORMAL_COMMUNICATION = 1,
  Message_ChannelState_CHANNEL_SHUTDOWN = 2,
  Message_ChannelState_Message_ChannelState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Message_ChannelState_Message_ChannelState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Message_ChannelState_IsValid(int value);
constexpr Message_ChannelState Message_ChannelState_ChannelState_MIN = Message_ChannelState_INITIAL_STARTUP;
constexpr Message_ChannelState Message_ChannelState_ChannelState_MAX = Message_ChannelState_CHANNEL_SHUTDOWN;
constexpr int Message_ChannelState_ChannelState_ARRAYSIZE = Message_ChannelState_ChannelState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Message_ChannelState_descriptor();
template<typename T>
inline const std::string& Message_ChannelState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Message_ChannelState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Message_ChannelState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Message_ChannelState_descriptor(), enum_t_value);
}
inline bool Message_ChannelState_Parse(
    const std::string& name, Message_ChannelState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Message_ChannelState>(
    Message_ChannelState_descriptor(), name, value);
}
enum Message_MessageType : int {
  Message_MessageType_INFORMATION = 0,
  Message_MessageType_KEYSPACE = 1,
  Message_MessageType_DATA_REPLICATION_UNUSED = 2,
  Message_MessageType_Message_MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Message_MessageType_Message_MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Message_MessageType_IsValid(int value);
constexpr Message_MessageType Message_MessageType_MessageType_MIN = Message_MessageType_INFORMATION;
constexpr Message_MessageType Message_MessageType_MessageType_MAX = Message_MessageType_DATA_REPLICATION_UNUSED;
constexpr int Message_MessageType_MessageType_ARRAYSIZE = Message_MessageType_MessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Message_MessageType_descriptor();
template<typename T>
inline const std::string& Message_MessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Message_MessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Message_MessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Message_MessageType_descriptor(), enum_t_value);
}
inline bool Message_MessageType_Parse(
    const std::string& name, Message_MessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Message_MessageType>(
    Message_MessageType_descriptor(), name, value);
}
// ===================================================================

class InformationalMessageContents_CollectionInformationRecord_CreationRateData :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:InformationalMessageContents.CollectionInformationRecord.CreationRateData) */ {
 public:
  InformationalMessageContents_CollectionInformationRecord_CreationRateData();
  virtual ~InformationalMessageContents_CollectionInformationRecord_CreationRateData();

  InformationalMessageContents_CollectionInformationRecord_CreationRateData(const InformationalMessageContents_CollectionInformationRecord_CreationRateData& from);
  InformationalMessageContents_CollectionInformationRecord_CreationRateData(InformationalMessageContents_CollectionInformationRecord_CreationRateData&& from) noexcept
    : InformationalMessageContents_CollectionInformationRecord_CreationRateData() {
    *this = ::std::move(from);
  }

  inline InformationalMessageContents_CollectionInformationRecord_CreationRateData& operator=(const InformationalMessageContents_CollectionInformationRecord_CreationRateData& from) {
    CopyFrom(from);
    return *this;
  }
  inline InformationalMessageContents_CollectionInformationRecord_CreationRateData& operator=(InformationalMessageContents_CollectionInformationRecord_CreationRateData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const InformationalMessageContents_CollectionInformationRecord_CreationRateData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InformationalMessageContents_CollectionInformationRecord_CreationRateData* internal_default_instance() {
    return reinterpret_cast<const InformationalMessageContents_CollectionInformationRecord_CreationRateData*>(
               &_InformationalMessageContents_CollectionInformationRecord_CreationRateData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(InformationalMessageContents_CollectionInformationRecord_CreationRateData& a, InformationalMessageContents_CollectionInformationRecord_CreationRateData& b) {
    a.Swap(&b);
  }
  inline void Swap(InformationalMessageContents_CollectionInformationRecord_CreationRateData* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline InformationalMessageContents_CollectionInformationRecord_CreationRateData* New() const final {
    return CreateMaybeMessage<InformationalMessageContents_CollectionInformationRecord_CreationRateData>(nullptr);
  }

  InformationalMessageContents_CollectionInformationRecord_CreationRateData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<InformationalMessageContents_CollectionInformationRecord_CreationRateData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const InformationalMessageContents_CollectionInformationRecord_CreationRateData& from);
  void MergeFrom(const InformationalMessageContents_CollectionInformationRecord_CreationRateData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InformationalMessageContents_CollectionInformationRecord_CreationRateData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "InformationalMessageContents.CollectionInformationRecord.CreationRateData";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kShortAllocationRatioFieldNumber = 1,
    kLongAllocationRatioFieldNumber = 2,
    kCreatedPreviousDayFieldNumber = 3,
    kCreatedPreviousWeekFieldNumber = 4,
  };
  // double shortAllocationRatio = 1;
  void clear_shortallocationratio();
  double shortallocationratio() const;
  void set_shortallocationratio(double value);
  private:
  double _internal_shortallocationratio() const;
  void _internal_set_shortallocationratio(double value);
  public:

  // double longAllocationRatio = 2;
  void clear_longallocationratio();
  double longallocationratio() const;
  void set_longallocationratio(double value);
  private:
  double _internal_longallocationratio() const;
  void _internal_set_longallocationratio(double value);
  public:

  // double createdPreviousDay = 3;
  void clear_createdpreviousday();
  double createdpreviousday() const;
  void set_createdpreviousday(double value);
  private:
  double _internal_createdpreviousday() const;
  void _internal_set_createdpreviousday(double value);
  public:

  // double createdPreviousWeek = 4;
  void clear_createdpreviousweek();
  double createdpreviousweek() const;
  void set_createdpreviousweek(double value);
  private:
  double _internal_createdpreviousweek() const;
  void _internal_set_createdpreviousweek(double value);
  public:

  // @@protoc_insertion_point(class_scope:InformationalMessageContents.CollectionInformationRecord.CreationRateData)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  double shortallocationratio_;
  double longallocationratio_;
  double createdpreviousday_;
  double createdpreviousweek_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class InformationalMessageContents_CollectionInformationRecord :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:InformationalMessageContents.CollectionInformationRecord) */ {
 public:
  InformationalMessageContents_CollectionInformationRecord();
  virtual ~InformationalMessageContents_CollectionInformationRecord();

  InformationalMessageContents_CollectionInformationRecord(const InformationalMessageContents_CollectionInformationRecord& from);
  InformationalMessageContents_CollectionInformationRecord(InformationalMessageContents_CollectionInformationRecord&& from) noexcept
    : InformationalMessageContents_CollectionInformationRecord() {
    *this = ::std::move(from);
  }

  inline InformationalMessageContents_CollectionInformationRecord& operator=(const InformationalMessageContents_CollectionInformationRecord& from) {
    CopyFrom(from);
    return *this;
  }
  inline InformationalMessageContents_CollectionInformationRecord& operator=(InformationalMessageContents_CollectionInformationRecord&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const InformationalMessageContents_CollectionInformationRecord& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InformationalMessageContents_CollectionInformationRecord* internal_default_instance() {
    return reinterpret_cast<const InformationalMessageContents_CollectionInformationRecord*>(
               &_InformationalMessageContents_CollectionInformationRecord_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(InformationalMessageContents_CollectionInformationRecord& a, InformationalMessageContents_CollectionInformationRecord& b) {
    a.Swap(&b);
  }
  inline void Swap(InformationalMessageContents_CollectionInformationRecord* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline InformationalMessageContents_CollectionInformationRecord* New() const final {
    return CreateMaybeMessage<InformationalMessageContents_CollectionInformationRecord>(nullptr);
  }

  InformationalMessageContents_CollectionInformationRecord* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<InformationalMessageContents_CollectionInformationRecord>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const InformationalMessageContents_CollectionInformationRecord& from);
  void MergeFrom(const InformationalMessageContents_CollectionInformationRecord& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InformationalMessageContents_CollectionInformationRecord* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "InformationalMessageContents.CollectionInformationRecord";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef InformationalMessageContents_CollectionInformationRecord_CreationRateData CreationRateData;

  // accessors -------------------------------------------------------

  enum : int {
    kCollectionNameFieldNumber = 1,
    kCreationRateDataFieldNumber = 2,
  };
  // string collectionName = 1;
  void clear_collectionname();
  const std::string& collectionname() const;
  void set_collectionname(const std::string& value);
  void set_collectionname(std::string&& value);
  void set_collectionname(const char* value);
  void set_collectionname(const char* value, size_t size);
  std::string* mutable_collectionname();
  std::string* release_collectionname();
  void set_allocated_collectionname(std::string* collectionname);
  private:
  const std::string& _internal_collectionname() const;
  void _internal_set_collectionname(const std::string& value);
  std::string* _internal_mutable_collectionname();
  public:

  // .InformationalMessageContents.CollectionInformationRecord.CreationRateData creationRateData = 2;
  bool has_creationratedata() const;
  private:
  bool _internal_has_creationratedata() const;
  public:
  void clear_creationratedata();
  const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData& creationratedata() const;
  ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* release_creationratedata();
  ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* mutable_creationratedata();
  void set_allocated_creationratedata(::InformationalMessageContents_CollectionInformationRecord_CreationRateData* creationratedata);
  private:
  const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData& _internal_creationratedata() const;
  ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* _internal_mutable_creationratedata();
  public:

  // @@protoc_insertion_point(class_scope:InformationalMessageContents.CollectionInformationRecord)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr collectionname_;
  ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* creationratedata_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class InformationalMessageContents :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:InformationalMessageContents) */ {
 public:
  InformationalMessageContents();
  virtual ~InformationalMessageContents();

  InformationalMessageContents(const InformationalMessageContents& from);
  InformationalMessageContents(InformationalMessageContents&& from) noexcept
    : InformationalMessageContents() {
    *this = ::std::move(from);
  }

  inline InformationalMessageContents& operator=(const InformationalMessageContents& from) {
    CopyFrom(from);
    return *this;
  }
  inline InformationalMessageContents& operator=(InformationalMessageContents&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const InformationalMessageContents& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InformationalMessageContents* internal_default_instance() {
    return reinterpret_cast<const InformationalMessageContents*>(
               &_InformationalMessageContents_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(InformationalMessageContents& a, InformationalMessageContents& b) {
    a.Swap(&b);
  }
  inline void Swap(InformationalMessageContents* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline InformationalMessageContents* New() const final {
    return CreateMaybeMessage<InformationalMessageContents>(nullptr);
  }

  InformationalMessageContents* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<InformationalMessageContents>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const InformationalMessageContents& from);
  void MergeFrom(const InformationalMessageContents& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InformationalMessageContents* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "InformationalMessageContents";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef InformationalMessageContents_CollectionInformationRecord CollectionInformationRecord;

  // accessors -------------------------------------------------------

  enum : int {
    kRecordsFieldNumber = 1,
  };
  // repeated .InformationalMessageContents.CollectionInformationRecord records = 1;
  int records_size() const;
  private:
  int _internal_records_size() const;
  public:
  void clear_records();
  ::InformationalMessageContents_CollectionInformationRecord* mutable_records(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::InformationalMessageContents_CollectionInformationRecord >*
      mutable_records();
  private:
  const ::InformationalMessageContents_CollectionInformationRecord& _internal_records(int index) const;
  ::InformationalMessageContents_CollectionInformationRecord* _internal_add_records();
  public:
  const ::InformationalMessageContents_CollectionInformationRecord& records(int index) const;
  ::InformationalMessageContents_CollectionInformationRecord* add_records();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::InformationalMessageContents_CollectionInformationRecord >&
      records() const;

  // @@protoc_insertion_point(class_scope:InformationalMessageContents)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::InformationalMessageContents_CollectionInformationRecord > records_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class KeyspaceMessageContents_Keyspace :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:KeyspaceMessageContents.Keyspace) */ {
 public:
  KeyspaceMessageContents_Keyspace();
  virtual ~KeyspaceMessageContents_Keyspace();

  KeyspaceMessageContents_Keyspace(const KeyspaceMessageContents_Keyspace& from);
  KeyspaceMessageContents_Keyspace(KeyspaceMessageContents_Keyspace&& from) noexcept
    : KeyspaceMessageContents_Keyspace() {
    *this = ::std::move(from);
  }

  inline KeyspaceMessageContents_Keyspace& operator=(const KeyspaceMessageContents_Keyspace& from) {
    CopyFrom(from);
    return *this;
  }
  inline KeyspaceMessageContents_Keyspace& operator=(KeyspaceMessageContents_Keyspace&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const KeyspaceMessageContents_Keyspace& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const KeyspaceMessageContents_Keyspace* internal_default_instance() {
    return reinterpret_cast<const KeyspaceMessageContents_Keyspace*>(
               &_KeyspaceMessageContents_Keyspace_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(KeyspaceMessageContents_Keyspace& a, KeyspaceMessageContents_Keyspace& b) {
    a.Swap(&b);
  }
  inline void Swap(KeyspaceMessageContents_Keyspace* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline KeyspaceMessageContents_Keyspace* New() const final {
    return CreateMaybeMessage<KeyspaceMessageContents_Keyspace>(nullptr);
  }

  KeyspaceMessageContents_Keyspace* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<KeyspaceMessageContents_Keyspace>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const KeyspaceMessageContents_Keyspace& from);
  void MergeFrom(const KeyspaceMessageContents_Keyspace& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KeyspaceMessageContents_Keyspace* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "KeyspaceMessageContents.Keyspace";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kStartIDFieldNumber = 2,
    kEndIDFieldNumber = 3,
    kSuffixBitsFieldNumber = 4,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // uint32 startID = 2;
  void clear_startid();
  ::PROTOBUF_NAMESPACE_ID::uint32 startid() const;
  void set_startid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_startid() const;
  void _internal_set_startid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 endID = 3;
  void clear_endid();
  ::PROTOBUF_NAMESPACE_ID::uint32 endid() const;
  void set_endid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_endid() const;
  void _internal_set_endid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 suffixBits = 4;
  void clear_suffixbits();
  ::PROTOBUF_NAMESPACE_ID::uint32 suffixbits() const;
  void set_suffixbits(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_suffixbits() const;
  void _internal_set_suffixbits(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:KeyspaceMessageContents.Keyspace)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::uint32 startid_;
  ::PROTOBUF_NAMESPACE_ID::uint32 endid_;
  ::PROTOBUF_NAMESPACE_ID::uint32 suffixbits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class KeyspaceMessageContents :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:KeyspaceMessageContents) */ {
 public:
  KeyspaceMessageContents();
  virtual ~KeyspaceMessageContents();

  KeyspaceMessageContents(const KeyspaceMessageContents& from);
  KeyspaceMessageContents(KeyspaceMessageContents&& from) noexcept
    : KeyspaceMessageContents() {
    *this = ::std::move(from);
  }

  inline KeyspaceMessageContents& operator=(const KeyspaceMessageContents& from) {
    CopyFrom(from);
    return *this;
  }
  inline KeyspaceMessageContents& operator=(KeyspaceMessageContents&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const KeyspaceMessageContents& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const KeyspaceMessageContents* internal_default_instance() {
    return reinterpret_cast<const KeyspaceMessageContents*>(
               &_KeyspaceMessageContents_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(KeyspaceMessageContents& a, KeyspaceMessageContents& b) {
    a.Swap(&b);
  }
  inline void Swap(KeyspaceMessageContents* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline KeyspaceMessageContents* New() const final {
    return CreateMaybeMessage<KeyspaceMessageContents>(nullptr);
  }

  KeyspaceMessageContents* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<KeyspaceMessageContents>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const KeyspaceMessageContents& from);
  void MergeFrom(const KeyspaceMessageContents& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KeyspaceMessageContents* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "KeyspaceMessageContents";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef KeyspaceMessageContents_Keyspace Keyspace;

  // accessors -------------------------------------------------------

  enum : int {
    kKeyspacesFieldNumber = 1,
  };
  // repeated .KeyspaceMessageContents.Keyspace keyspaces = 1;
  int keyspaces_size() const;
  private:
  int _internal_keyspaces_size() const;
  public:
  void clear_keyspaces();
  ::KeyspaceMessageContents_Keyspace* mutable_keyspaces(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::KeyspaceMessageContents_Keyspace >*
      mutable_keyspaces();
  private:
  const ::KeyspaceMessageContents_Keyspace& _internal_keyspaces(int index) const;
  ::KeyspaceMessageContents_Keyspace* _internal_add_keyspaces();
  public:
  const ::KeyspaceMessageContents_Keyspace& keyspaces(int index) const;
  ::KeyspaceMessageContents_Keyspace* add_keyspaces();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::KeyspaceMessageContents_Keyspace >&
      keyspaces() const;

  // @@protoc_insertion_point(class_scope:KeyspaceMessageContents)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::KeyspaceMessageContents_Keyspace > keyspaces_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class Message :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Message& default_instance();

  enum MessageCase {
    kInfo = 8,
    kKeyspace = 9,
    MESSAGE_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }
  inline void Swap(Message* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Message* New() const final {
    return CreateMaybeMessage<Message>(nullptr);
  }

  Message* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Message";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Message_ChannelState ChannelState;
  static constexpr ChannelState INITIAL_STARTUP =
    Message_ChannelState_INITIAL_STARTUP;
  static constexpr ChannelState NORMAL_COMMUNICATION =
    Message_ChannelState_NORMAL_COMMUNICATION;
  static constexpr ChannelState CHANNEL_SHUTDOWN =
    Message_ChannelState_CHANNEL_SHUTDOWN;
  static inline bool ChannelState_IsValid(int value) {
    return Message_ChannelState_IsValid(value);
  }
  static constexpr ChannelState ChannelState_MIN =
    Message_ChannelState_ChannelState_MIN;
  static constexpr ChannelState ChannelState_MAX =
    Message_ChannelState_ChannelState_MAX;
  static constexpr int ChannelState_ARRAYSIZE =
    Message_ChannelState_ChannelState_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  ChannelState_descriptor() {
    return Message_ChannelState_descriptor();
  }
  template<typename T>
  static inline const std::string& ChannelState_Name(T enum_t_value) {
    static_assert(::std::is_same<T, ChannelState>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function ChannelState_Name.");
    return Message_ChannelState_Name(enum_t_value);
  }
  static inline bool ChannelState_Parse(const std::string& name,
      ChannelState* value) {
    return Message_ChannelState_Parse(name, value);
  }

  typedef Message_MessageType MessageType;
  static constexpr MessageType INFORMATION =
    Message_MessageType_INFORMATION;
  static constexpr MessageType KEYSPACE =
    Message_MessageType_KEYSPACE;
  static constexpr MessageType DATA_REPLICATION_UNUSED =
    Message_MessageType_DATA_REPLICATION_UNUSED;
  static inline bool MessageType_IsValid(int value) {
    return Message_MessageType_IsValid(value);
  }
  static constexpr MessageType MessageType_MIN =
    Message_MessageType_MessageType_MIN;
  static constexpr MessageType MessageType_MAX =
    Message_MessageType_MessageType_MAX;
  static constexpr int MessageType_ARRAYSIZE =
    Message_MessageType_MessageType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  MessageType_descriptor() {
    return Message_MessageType_descriptor();
  }
  template<typename T>
  static inline const std::string& MessageType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MessageType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MessageType_Name.");
    return Message_MessageType_Name(enum_t_value);
  }
  static inline bool MessageType_Parse(const std::string& name,
      MessageType* value) {
    return Message_MessageType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSourceNodeIDFieldNumber = 1,
    kDestNodeIDFieldNumber = 2,
    kTimestampFieldNumber = 5,
    kLastReceivedMsgFieldNumber = 3,
    kChannelStateFieldNumber = 4,
    kMessageIDFieldNumber = 6,
    kMessageTypeFieldNumber = 7,
    kInfoFieldNumber = 8,
    kKeyspaceFieldNumber = 9,
  };
  // bytes sourceNodeID = 1;
  void clear_sourcenodeid();
  const std::string& sourcenodeid() const;
  void set_sourcenodeid(const std::string& value);
  void set_sourcenodeid(std::string&& value);
  void set_sourcenodeid(const char* value);
  void set_sourcenodeid(const void* value, size_t size);
  std::string* mutable_sourcenodeid();
  std::string* release_sourcenodeid();
  void set_allocated_sourcenodeid(std::string* sourcenodeid);
  private:
  const std::string& _internal_sourcenodeid() const;
  void _internal_set_sourcenodeid(const std::string& value);
  std::string* _internal_mutable_sourcenodeid();
  public:

  // bytes destNodeID = 2;
  void clear_destnodeid();
  const std::string& destnodeid() const;
  void set_destnodeid(const std::string& value);
  void set_destnodeid(std::string&& value);
  void set_destnodeid(const char* value);
  void set_destnodeid(const void* value, size_t size);
  std::string* mutable_destnodeid();
  std::string* release_destnodeid();
  void set_allocated_destnodeid(std::string* destnodeid);
  private:
  const std::string& _internal_destnodeid() const;
  void _internal_set_destnodeid(const std::string& value);
  std::string* _internal_mutable_destnodeid();
  public:

  // .google.protobuf.Timestamp timestamp = 5;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:

  // uint32 lastReceivedMsg = 3;
  void clear_lastreceivedmsg();
  ::PROTOBUF_NAMESPACE_ID::uint32 lastreceivedmsg() const;
  void set_lastreceivedmsg(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_lastreceivedmsg() const;
  void _internal_set_lastreceivedmsg(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // .Message.ChannelState channelState = 4;
  void clear_channelstate();
  ::Message_ChannelState channelstate() const;
  void set_channelstate(::Message_ChannelState value);
  private:
  ::Message_ChannelState _internal_channelstate() const;
  void _internal_set_channelstate(::Message_ChannelState value);
  public:

  // sint64 messageID = 6;
  void clear_messageid();
  ::PROTOBUF_NAMESPACE_ID::int64 messageid() const;
  void set_messageid(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_messageid() const;
  void _internal_set_messageid(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // .Message.MessageType messageType = 7;
  void clear_messagetype();
  ::Message_MessageType messagetype() const;
  void set_messagetype(::Message_MessageType value);
  private:
  ::Message_MessageType _internal_messagetype() const;
  void _internal_set_messagetype(::Message_MessageType value);
  public:

  // .InformationalMessageContents info = 8;
  bool has_info() const;
  private:
  bool _internal_has_info() const;
  public:
  void clear_info();
  const ::InformationalMessageContents& info() const;
  ::InformationalMessageContents* release_info();
  ::InformationalMessageContents* mutable_info();
  void set_allocated_info(::InformationalMessageContents* info);
  private:
  const ::InformationalMessageContents& _internal_info() const;
  ::InformationalMessageContents* _internal_mutable_info();
  public:

  // .KeyspaceMessageContents keyspace = 9;
  bool has_keyspace() const;
  private:
  bool _internal_has_keyspace() const;
  public:
  void clear_keyspace();
  const ::KeyspaceMessageContents& keyspace() const;
  ::KeyspaceMessageContents* release_keyspace();
  ::KeyspaceMessageContents* mutable_keyspace();
  void set_allocated_keyspace(::KeyspaceMessageContents* keyspace);
  private:
  const ::KeyspaceMessageContents& _internal_keyspace() const;
  ::KeyspaceMessageContents* _internal_mutable_keyspace();
  public:

  void clear_message();
  MessageCase message_case() const;
  // @@protoc_insertion_point(class_scope:Message)
 private:
  class _Internal;
  void set_has_info();
  void set_has_keyspace();

  inline bool has_message() const;
  inline void clear_has_message();

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sourcenodeid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr destnodeid_;
  PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint32 lastreceivedmsg_;
  int channelstate_;
  ::PROTOBUF_NAMESPACE_ID::int64 messageid_;
  int messagetype_;
  union MessageUnion {
    MessageUnion() {}
    ::InformationalMessageContents* info_;
    ::KeyspaceMessageContents* keyspace_;
  } message_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_message_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InformationalMessageContents_CollectionInformationRecord_CreationRateData

// double shortAllocationRatio = 1;
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::clear_shortallocationratio() {
  shortallocationratio_ = 0;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_shortallocationratio() const {
  return shortallocationratio_;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::shortallocationratio() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.CreationRateData.shortAllocationRatio)
  return _internal_shortallocationratio();
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_set_shortallocationratio(double value) {
  
  shortallocationratio_ = value;
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::set_shortallocationratio(double value) {
  _internal_set_shortallocationratio(value);
  // @@protoc_insertion_point(field_set:InformationalMessageContents.CollectionInformationRecord.CreationRateData.shortAllocationRatio)
}

// double longAllocationRatio = 2;
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::clear_longallocationratio() {
  longallocationratio_ = 0;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_longallocationratio() const {
  return longallocationratio_;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::longallocationratio() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.CreationRateData.longAllocationRatio)
  return _internal_longallocationratio();
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_set_longallocationratio(double value) {
  
  longallocationratio_ = value;
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::set_longallocationratio(double value) {
  _internal_set_longallocationratio(value);
  // @@protoc_insertion_point(field_set:InformationalMessageContents.CollectionInformationRecord.CreationRateData.longAllocationRatio)
}

// double createdPreviousDay = 3;
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::clear_createdpreviousday() {
  createdpreviousday_ = 0;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_createdpreviousday() const {
  return createdpreviousday_;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::createdpreviousday() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.CreationRateData.createdPreviousDay)
  return _internal_createdpreviousday();
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_set_createdpreviousday(double value) {
  
  createdpreviousday_ = value;
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::set_createdpreviousday(double value) {
  _internal_set_createdpreviousday(value);
  // @@protoc_insertion_point(field_set:InformationalMessageContents.CollectionInformationRecord.CreationRateData.createdPreviousDay)
}

// double createdPreviousWeek = 4;
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::clear_createdpreviousweek() {
  createdpreviousweek_ = 0;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_createdpreviousweek() const {
  return createdpreviousweek_;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::createdpreviousweek() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.CreationRateData.createdPreviousWeek)
  return _internal_createdpreviousweek();
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_set_createdpreviousweek(double value) {
  
  createdpreviousweek_ = value;
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::set_createdpreviousweek(double value) {
  _internal_set_createdpreviousweek(value);
  // @@protoc_insertion_point(field_set:InformationalMessageContents.CollectionInformationRecord.CreationRateData.createdPreviousWeek)
}

// -------------------------------------------------------------------

// InformationalMessageContents_CollectionInformationRecord

// string collectionName = 1;
inline void InformationalMessageContents_CollectionInformationRecord::clear_collectionname() {
  collectionname_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& InformationalMessageContents_CollectionInformationRecord::collectionname() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.collectionName)
  return _internal_collectionname();
}
inline void InformationalMessageContents_CollectionInformationRecord::set_collectionname(const std::string& value) {
  _internal_set_collectionname(value);
  // @@protoc_insertion_point(field_set:InformationalMessageContents.CollectionInformationRecord.collectionName)
}
inline std::string* InformationalMessageContents_CollectionInformationRecord::mutable_collectionname() {
  // @@protoc_insertion_point(field_mutable:InformationalMessageContents.CollectionInformationRecord.collectionName)
  return _internal_mutable_collectionname();
}
inline const std::string& InformationalMessageContents_CollectionInformationRecord::_internal_collectionname() const {
  return collectionname_.GetNoArena();
}
inline void InformationalMessageContents_CollectionInformationRecord::_internal_set_collectionname(const std::string& value) {
  
  collectionname_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void InformationalMessageContents_CollectionInformationRecord::set_collectionname(std::string&& value) {
  
  collectionname_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:InformationalMessageContents.CollectionInformationRecord.collectionName)
}
inline void InformationalMessageContents_CollectionInformationRecord::set_collectionname(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  collectionname_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:InformationalMessageContents.CollectionInformationRecord.collectionName)
}
inline void InformationalMessageContents_CollectionInformationRecord::set_collectionname(const char* value, size_t size) {
  
  collectionname_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:InformationalMessageContents.CollectionInformationRecord.collectionName)
}
inline std::string* InformationalMessageContents_CollectionInformationRecord::_internal_mutable_collectionname() {
  
  return collectionname_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* InformationalMessageContents_CollectionInformationRecord::release_collectionname() {
  // @@protoc_insertion_point(field_release:InformationalMessageContents.CollectionInformationRecord.collectionName)
  
  return collectionname_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void InformationalMessageContents_CollectionInformationRecord::set_allocated_collectionname(std::string* collectionname) {
  if (collectionname != nullptr) {
    
  } else {
    
  }
  collectionname_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), collectionname);
  // @@protoc_insertion_point(field_set_allocated:InformationalMessageContents.CollectionInformationRecord.collectionName)
}

// .InformationalMessageContents.CollectionInformationRecord.CreationRateData creationRateData = 2;
inline bool InformationalMessageContents_CollectionInformationRecord::_internal_has_creationratedata() const {
  return this != internal_default_instance() && creationratedata_ != nullptr;
}
inline bool InformationalMessageContents_CollectionInformationRecord::has_creationratedata() const {
  return _internal_has_creationratedata();
}
inline void InformationalMessageContents_CollectionInformationRecord::clear_creationratedata() {
  if (GetArenaNoVirtual() == nullptr && creationratedata_ != nullptr) {
    delete creationratedata_;
  }
  creationratedata_ = nullptr;
}
inline const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData& InformationalMessageContents_CollectionInformationRecord::_internal_creationratedata() const {
  const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* p = creationratedata_;
  return p != nullptr ? *p : *reinterpret_cast<const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData*>(
      &::_InformationalMessageContents_CollectionInformationRecord_CreationRateData_default_instance_);
}
inline const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData& InformationalMessageContents_CollectionInformationRecord::creationratedata() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.creationRateData)
  return _internal_creationratedata();
}
inline ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* InformationalMessageContents_CollectionInformationRecord::release_creationratedata() {
  // @@protoc_insertion_point(field_release:InformationalMessageContents.CollectionInformationRecord.creationRateData)
  
  ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* temp = creationratedata_;
  creationratedata_ = nullptr;
  return temp;
}
inline ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* InformationalMessageContents_CollectionInformationRecord::_internal_mutable_creationratedata() {
  
  if (creationratedata_ == nullptr) {
    auto* p = CreateMaybeMessage<::InformationalMessageContents_CollectionInformationRecord_CreationRateData>(GetArenaNoVirtual());
    creationratedata_ = p;
  }
  return creationratedata_;
}
inline ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* InformationalMessageContents_CollectionInformationRecord::mutable_creationratedata() {
  // @@protoc_insertion_point(field_mutable:InformationalMessageContents.CollectionInformationRecord.creationRateData)
  return _internal_mutable_creationratedata();
}
inline void InformationalMessageContents_CollectionInformationRecord::set_allocated_creationratedata(::InformationalMessageContents_CollectionInformationRecord_CreationRateData* creationratedata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete creationratedata_;
  }
  if (creationratedata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      creationratedata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, creationratedata, submessage_arena);
    }
    
  } else {
    
  }
  creationratedata_ = creationratedata;
  // @@protoc_insertion_point(field_set_allocated:InformationalMessageContents.CollectionInformationRecord.creationRateData)
}

// -------------------------------------------------------------------

// InformationalMessageContents

// repeated .InformationalMessageContents.CollectionInformationRecord records = 1;
inline int InformationalMessageContents::_internal_records_size() const {
  return records_.size();
}
inline int InformationalMessageContents::records_size() const {
  return _internal_records_size();
}
inline void InformationalMessageContents::clear_records() {
  records_.Clear();
}
inline ::InformationalMessageContents_CollectionInformationRecord* InformationalMessageContents::mutable_records(int index) {
  // @@protoc_insertion_point(field_mutable:InformationalMessageContents.records)
  return records_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::InformationalMessageContents_CollectionInformationRecord >*
InformationalMessageContents::mutable_records() {
  // @@protoc_insertion_point(field_mutable_list:InformationalMessageContents.records)
  return &records_;
}
inline const ::InformationalMessageContents_CollectionInformationRecord& InformationalMessageContents::_internal_records(int index) const {
  return records_.Get(index);
}
inline const ::InformationalMessageContents_CollectionInformationRecord& InformationalMessageContents::records(int index) const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.records)
  return _internal_records(index);
}
inline ::InformationalMessageContents_CollectionInformationRecord* InformationalMessageContents::_internal_add_records() {
  return records_.Add();
}
inline ::InformationalMessageContents_CollectionInformationRecord* InformationalMessageContents::add_records() {
  // @@protoc_insertion_point(field_add:InformationalMessageContents.records)
  return _internal_add_records();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::InformationalMessageContents_CollectionInformationRecord >&
InformationalMessageContents::records() const {
  // @@protoc_insertion_point(field_list:InformationalMessageContents.records)
  return records_;
}

// -------------------------------------------------------------------

// KeyspaceMessageContents_Keyspace

// string name = 1;
inline void KeyspaceMessageContents_Keyspace::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& KeyspaceMessageContents_Keyspace::name() const {
  // @@protoc_insertion_point(field_get:KeyspaceMessageContents.Keyspace.name)
  return _internal_name();
}
inline void KeyspaceMessageContents_Keyspace::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:KeyspaceMessageContents.Keyspace.name)
}
inline std::string* KeyspaceMessageContents_Keyspace::mutable_name() {
  // @@protoc_insertion_point(field_mutable:KeyspaceMessageContents.Keyspace.name)
  return _internal_mutable_name();
}
inline const std::string& KeyspaceMessageContents_Keyspace::_internal_name() const {
  return name_.GetNoArena();
}
inline void KeyspaceMessageContents_Keyspace::_internal_set_name(const std::string& value) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void KeyspaceMessageContents_Keyspace::set_name(std::string&& value) {
  
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:KeyspaceMessageContents.Keyspace.name)
}
inline void KeyspaceMessageContents_Keyspace::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:KeyspaceMessageContents.Keyspace.name)
}
inline void KeyspaceMessageContents_Keyspace::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:KeyspaceMessageContents.Keyspace.name)
}
inline std::string* KeyspaceMessageContents_Keyspace::_internal_mutable_name() {
  
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* KeyspaceMessageContents_Keyspace::release_name() {
  // @@protoc_insertion_point(field_release:KeyspaceMessageContents.Keyspace.name)
  
  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void KeyspaceMessageContents_Keyspace::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:KeyspaceMessageContents.Keyspace.name)
}

// uint32 startID = 2;
inline void KeyspaceMessageContents_Keyspace::clear_startid() {
  startid_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 KeyspaceMessageContents_Keyspace::_internal_startid() const {
  return startid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 KeyspaceMessageContents_Keyspace::startid() const {
  // @@protoc_insertion_point(field_get:KeyspaceMessageContents.Keyspace.startID)
  return _internal_startid();
}
inline void KeyspaceMessageContents_Keyspace::_internal_set_startid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  startid_ = value;
}
inline void KeyspaceMessageContents_Keyspace::set_startid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_startid(value);
  // @@protoc_insertion_point(field_set:KeyspaceMessageContents.Keyspace.startID)
}

// uint32 endID = 3;
inline void KeyspaceMessageContents_Keyspace::clear_endid() {
  endid_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 KeyspaceMessageContents_Keyspace::_internal_endid() const {
  return endid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 KeyspaceMessageContents_Keyspace::endid() const {
  // @@protoc_insertion_point(field_get:KeyspaceMessageContents.Keyspace.endID)
  return _internal_endid();
}
inline void KeyspaceMessageContents_Keyspace::_internal_set_endid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  endid_ = value;
}
inline void KeyspaceMessageContents_Keyspace::set_endid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_endid(value);
  // @@protoc_insertion_point(field_set:KeyspaceMessageContents.Keyspace.endID)
}

// uint32 suffixBits = 4;
inline void KeyspaceMessageContents_Keyspace::clear_suffixbits() {
  suffixbits_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 KeyspaceMessageContents_Keyspace::_internal_suffixbits() const {
  return suffixbits_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 KeyspaceMessageContents_Keyspace::suffixbits() const {
  // @@protoc_insertion_point(field_get:KeyspaceMessageContents.Keyspace.suffixBits)
  return _internal_suffixbits();
}
inline void KeyspaceMessageContents_Keyspace::_internal_set_suffixbits(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  suffixbits_ = value;
}
inline void KeyspaceMessageContents_Keyspace::set_suffixbits(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_suffixbits(value);
  // @@protoc_insertion_point(field_set:KeyspaceMessageContents.Keyspace.suffixBits)
}

// -------------------------------------------------------------------

// KeyspaceMessageContents

// repeated .KeyspaceMessageContents.Keyspace keyspaces = 1;
inline int KeyspaceMessageContents::_internal_keyspaces_size() const {
  return keyspaces_.size();
}
inline int KeyspaceMessageContents::keyspaces_size() const {
  return _internal_keyspaces_size();
}
inline void KeyspaceMessageContents::clear_keyspaces() {
  keyspaces_.Clear();
}
inline ::KeyspaceMessageContents_Keyspace* KeyspaceMessageContents::mutable_keyspaces(int index) {
  // @@protoc_insertion_point(field_mutable:KeyspaceMessageContents.keyspaces)
  return keyspaces_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::KeyspaceMessageContents_Keyspace >*
KeyspaceMessageContents::mutable_keyspaces() {
  // @@protoc_insertion_point(field_mutable_list:KeyspaceMessageContents.keyspaces)
  return &keyspaces_;
}
inline const ::KeyspaceMessageContents_Keyspace& KeyspaceMessageContents::_internal_keyspaces(int index) const {
  return keyspaces_.Get(index);
}
inline const ::KeyspaceMessageContents_Keyspace& KeyspaceMessageContents::keyspaces(int index) const {
  // @@protoc_insertion_point(field_get:KeyspaceMessageContents.keyspaces)
  return _internal_keyspaces(index);
}
inline ::KeyspaceMessageContents_Keyspace* KeyspaceMessageContents::_internal_add_keyspaces() {
  return keyspaces_.Add();
}
inline ::KeyspaceMessageContents_Keyspace* KeyspaceMessageContents::add_keyspaces() {
  // @@protoc_insertion_point(field_add:KeyspaceMessageContents.keyspaces)
  return _internal_add_keyspaces();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::KeyspaceMessageContents_Keyspace >&
KeyspaceMessageContents::keyspaces() const {
  // @@protoc_insertion_point(field_list:KeyspaceMessageContents.keyspaces)
  return keyspaces_;
}

// -------------------------------------------------------------------

// Message

// bytes sourceNodeID = 1;
inline void Message::clear_sourcenodeid() {
  sourcenodeid_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Message::sourcenodeid() const {
  // @@protoc_insertion_point(field_get:Message.sourceNodeID)
  return _internal_sourcenodeid();
}
inline void Message::set_sourcenodeid(const std::string& value) {
  _internal_set_sourcenodeid(value);
  // @@protoc_insertion_point(field_set:Message.sourceNodeID)
}
inline std::string* Message::mutable_sourcenodeid() {
  // @@protoc_insertion_point(field_mutable:Message.sourceNodeID)
  return _internal_mutable_sourcenodeid();
}
inline const std::string& Message::_internal_sourcenodeid() const {
  return sourcenodeid_.GetNoArena();
}
inline void Message::_internal_set_sourcenodeid(const std::string& value) {
  
  sourcenodeid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Message::set_sourcenodeid(std::string&& value) {
  
  sourcenodeid_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.sourceNodeID)
}
inline void Message::set_sourcenodeid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  sourcenodeid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.sourceNodeID)
}
inline void Message::set_sourcenodeid(const void* value, size_t size) {
  
  sourcenodeid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.sourceNodeID)
}
inline std::string* Message::_internal_mutable_sourcenodeid() {
  
  return sourcenodeid_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Message::release_sourcenodeid() {
  // @@protoc_insertion_point(field_release:Message.sourceNodeID)
  
  return sourcenodeid_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_sourcenodeid(std::string* sourcenodeid) {
  if (sourcenodeid != nullptr) {
    
  } else {
    
  }
  sourcenodeid_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sourcenodeid);
  // @@protoc_insertion_point(field_set_allocated:Message.sourceNodeID)
}

// bytes destNodeID = 2;
inline void Message::clear_destnodeid() {
  destnodeid_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Message::destnodeid() const {
  // @@protoc_insertion_point(field_get:Message.destNodeID)
  return _internal_destnodeid();
}
inline void Message::set_destnodeid(const std::string& value) {
  _internal_set_destnodeid(value);
  // @@protoc_insertion_point(field_set:Message.destNodeID)
}
inline std::string* Message::mutable_destnodeid() {
  // @@protoc_insertion_point(field_mutable:Message.destNodeID)
  return _internal_mutable_destnodeid();
}
inline const std::string& Message::_internal_destnodeid() const {
  return destnodeid_.GetNoArena();
}
inline void Message::_internal_set_destnodeid(const std::string& value) {
  
  destnodeid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Message::set_destnodeid(std::string&& value) {
  
  destnodeid_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.destNodeID)
}
inline void Message::set_destnodeid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  destnodeid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.destNodeID)
}
inline void Message::set_destnodeid(const void* value, size_t size) {
  
  destnodeid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.destNodeID)
}
inline std::string* Message::_internal_mutable_destnodeid() {
  
  return destnodeid_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Message::release_destnodeid() {
  // @@protoc_insertion_point(field_release:Message.destNodeID)
  
  return destnodeid_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_destnodeid(std::string* destnodeid) {
  if (destnodeid != nullptr) {
    
  } else {
    
  }
  destnodeid_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), destnodeid);
  // @@protoc_insertion_point(field_set_allocated:Message.destNodeID)
}

// uint32 lastReceivedMsg = 3;
inline void Message::clear_lastreceivedmsg() {
  lastreceivedmsg_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Message::_internal_lastreceivedmsg() const {
  return lastreceivedmsg_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Message::lastreceivedmsg() const {
  // @@protoc_insertion_point(field_get:Message.lastReceivedMsg)
  return _internal_lastreceivedmsg();
}
inline void Message::_internal_set_lastreceivedmsg(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  lastreceivedmsg_ = value;
}
inline void Message::set_lastreceivedmsg(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_lastreceivedmsg(value);
  // @@protoc_insertion_point(field_set:Message.lastReceivedMsg)
}

// .Message.ChannelState channelState = 4;
inline void Message::clear_channelstate() {
  channelstate_ = 0;
}
inline ::Message_ChannelState Message::_internal_channelstate() const {
  return static_cast< ::Message_ChannelState >(channelstate_);
}
inline ::Message_ChannelState Message::channelstate() const {
  // @@protoc_insertion_point(field_get:Message.channelState)
  return _internal_channelstate();
}
inline void Message::_internal_set_channelstate(::Message_ChannelState value) {
  
  channelstate_ = value;
}
inline void Message::set_channelstate(::Message_ChannelState value) {
  _internal_set_channelstate(value);
  // @@protoc_insertion_point(field_set:Message.channelState)
}

// .google.protobuf.Timestamp timestamp = 5;
inline bool Message::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool Message::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Message::_internal_timestamp() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Message::timestamp() const {
  // @@protoc_insertion_point(field_get:Message.timestamp)
  return _internal_timestamp();
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Message::release_timestamp() {
  // @@protoc_insertion_point(field_release:Message.timestamp)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Message::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaNoVirtual());
    timestamp_ = p;
  }
  return timestamp_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Message::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:Message.timestamp)
  return _internal_mutable_timestamp();
}
inline void Message::set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:Message.timestamp)
}

// sint64 messageID = 6;
inline void Message::clear_messageid() {
  messageid_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Message::_internal_messageid() const {
  return messageid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Message::messageid() const {
  // @@protoc_insertion_point(field_get:Message.messageID)
  return _internal_messageid();
}
inline void Message::_internal_set_messageid(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  messageid_ = value;
}
inline void Message::set_messageid(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_messageid(value);
  // @@protoc_insertion_point(field_set:Message.messageID)
}

// .Message.MessageType messageType = 7;
inline void Message::clear_messagetype() {
  messagetype_ = 0;
}
inline ::Message_MessageType Message::_internal_messagetype() const {
  return static_cast< ::Message_MessageType >(messagetype_);
}
inline ::Message_MessageType Message::messagetype() const {
  // @@protoc_insertion_point(field_get:Message.messageType)
  return _internal_messagetype();
}
inline void Message::_internal_set_messagetype(::Message_MessageType value) {
  
  messagetype_ = value;
}
inline void Message::set_messagetype(::Message_MessageType value) {
  _internal_set_messagetype(value);
  // @@protoc_insertion_point(field_set:Message.messageType)
}

// .InformationalMessageContents info = 8;
inline bool Message::_internal_has_info() const {
  return message_case() == kInfo;
}
inline bool Message::has_info() const {
  return _internal_has_info();
}
inline void Message::set_has_info() {
  _oneof_case_[0] = kInfo;
}
inline void Message::clear_info() {
  if (_internal_has_info()) {
    delete message_.info_;
    clear_has_message();
  }
}
inline ::InformationalMessageContents* Message::release_info() {
  // @@protoc_insertion_point(field_release:Message.info)
  if (_internal_has_info()) {
    clear_has_message();
      ::InformationalMessageContents* temp = message_.info_;
    message_.info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::InformationalMessageContents& Message::_internal_info() const {
  return _internal_has_info()
      ? *message_.info_
      : *reinterpret_cast< ::InformationalMessageContents*>(&::_InformationalMessageContents_default_instance_);
}
inline const ::InformationalMessageContents& Message::info() const {
  // @@protoc_insertion_point(field_get:Message.info)
  return _internal_info();
}
inline ::InformationalMessageContents* Message::_internal_mutable_info() {
  if (!_internal_has_info()) {
    clear_message();
    set_has_info();
    message_.info_ = CreateMaybeMessage< ::InformationalMessageContents >(
        GetArenaNoVirtual());
  }
  return message_.info_;
}
inline ::InformationalMessageContents* Message::mutable_info() {
  // @@protoc_insertion_point(field_mutable:Message.info)
  return _internal_mutable_info();
}

// .KeyspaceMessageContents keyspace = 9;
inline bool Message::_internal_has_keyspace() const {
  return message_case() == kKeyspace;
}
inline bool Message::has_keyspace() const {
  return _internal_has_keyspace();
}
inline void Message::set_has_keyspace() {
  _oneof_case_[0] = kKeyspace;
}
inline void Message::clear_keyspace() {
  if (_internal_has_keyspace()) {
    delete message_.keyspace_;
    clear_has_message();
  }
}
inline ::KeyspaceMessageContents* Message::release_keyspace() {
  // @@protoc_insertion_point(field_release:Message.keyspace)
  if (_internal_has_keyspace()) {
    clear_has_message();
      ::KeyspaceMessageContents* temp = message_.keyspace_;
    message_.keyspace_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::KeyspaceMessageContents& Message::_internal_keyspace() const {
  return _internal_has_keyspace()
      ? *message_.keyspace_
      : *reinterpret_cast< ::KeyspaceMessageContents*>(&::_KeyspaceMessageContents_default_instance_);
}
inline const ::KeyspaceMessageContents& Message::keyspace() const {
  // @@protoc_insertion_point(field_get:Message.keyspace)
  return _internal_keyspace();
}
inline ::KeyspaceMessageContents* Message::_internal_mutable_keyspace() {
  if (!_internal_has_keyspace()) {
    clear_message();
    set_has_keyspace();
    message_.keyspace_ = CreateMaybeMessage< ::KeyspaceMessageContents >(
        GetArenaNoVirtual());
  }
  return message_.keyspace_;
}
inline ::KeyspaceMessageContents* Message::mutable_keyspace() {
  // @@protoc_insertion_point(field_mutable:Message.keyspace)
  return _internal_mutable_keyspace();
}

inline bool Message::has_message() const {
  return message_case() != MESSAGE_NOT_SET;
}
inline void Message::clear_has_message() {
  _oneof_case_[0] = MESSAGE_NOT_SET;
}
inline Message::MessageCase Message::message_case() const {
  return Message::MessageCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Message_ChannelState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Message_ChannelState>() {
  return ::Message_ChannelState_descriptor();
}
template <> struct is_proto_enum< ::Message_MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Message_MessageType>() {
  return ::Message_MessageType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_2eproto
