// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2eproto;
class InformationalMessageContents;
struct InformationalMessageContentsDefaultTypeInternal;
extern InformationalMessageContentsDefaultTypeInternal _InformationalMessageContents_default_instance_;
class InformationalMessageContents_CollectionInformationRecord;
struct InformationalMessageContents_CollectionInformationRecordDefaultTypeInternal;
extern InformationalMessageContents_CollectionInformationRecordDefaultTypeInternal _InformationalMessageContents_CollectionInformationRecord_default_instance_;
class InformationalMessageContents_CollectionInformationRecord_CreationRateData;
struct InformationalMessageContents_CollectionInformationRecord_CreationRateDataDefaultTypeInternal;
extern InformationalMessageContents_CollectionInformationRecord_CreationRateDataDefaultTypeInternal _InformationalMessageContents_CollectionInformationRecord_CreationRateData_default_instance_;
class KeyspaceMessageContents;
struct KeyspaceMessageContentsDefaultTypeInternal;
extern KeyspaceMessageContentsDefaultTypeInternal _KeyspaceMessageContents_default_instance_;
class KeyspaceMessageContents_Keyspace;
struct KeyspaceMessageContents_KeyspaceDefaultTypeInternal;
extern KeyspaceMessageContents_KeyspaceDefaultTypeInternal _KeyspaceMessageContents_Keyspace_default_instance_;
class Message;
struct MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::InformationalMessageContents* Arena::CreateMaybeMessage<::InformationalMessageContents>(Arena*);
template<> ::InformationalMessageContents_CollectionInformationRecord* Arena::CreateMaybeMessage<::InformationalMessageContents_CollectionInformationRecord>(Arena*);
template<> ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* Arena::CreateMaybeMessage<::InformationalMessageContents_CollectionInformationRecord_CreationRateData>(Arena*);
template<> ::KeyspaceMessageContents* Arena::CreateMaybeMessage<::KeyspaceMessageContents>(Arena*);
template<> ::KeyspaceMessageContents_Keyspace* Arena::CreateMaybeMessage<::KeyspaceMessageContents_Keyspace>(Arena*);
template<> ::Message* Arena::CreateMaybeMessage<::Message>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum Message_ChannelState : int {
  Message_ChannelState_INITIAL_STARTUP = 0,
  Message_ChannelState_NORMAL_COMMUNICATION = 1,
  Message_ChannelState_CHANNEL_SHUTDOWN = 2,
  Message_ChannelState_Message_ChannelState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Message_ChannelState_Message_ChannelState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Message_ChannelState_IsValid(int value);
constexpr Message_ChannelState Message_ChannelState_ChannelState_MIN = Message_ChannelState_INITIAL_STARTUP;
constexpr Message_ChannelState Message_ChannelState_ChannelState_MAX = Message_ChannelState_CHANNEL_SHUTDOWN;
constexpr int Message_ChannelState_ChannelState_ARRAYSIZE = Message_ChannelState_ChannelState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Message_ChannelState_descriptor();
template<typename T>
inline const std::string& Message_ChannelState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Message_ChannelState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Message_ChannelState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Message_ChannelState_descriptor(), enum_t_value);
}
inline bool Message_ChannelState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Message_ChannelState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Message_ChannelState>(
    Message_ChannelState_descriptor(), name, value);
}
enum Message_MessageType : int {
  Message_MessageType_INFORMATION = 0,
  Message_MessageType_KEYSPACE = 1,
  Message_MessageType_DATA_REPLICATION_UNUSED = 2,
  Message_MessageType_Message_MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Message_MessageType_Message_MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Message_MessageType_IsValid(int value);
constexpr Message_MessageType Message_MessageType_MessageType_MIN = Message_MessageType_INFORMATION;
constexpr Message_MessageType Message_MessageType_MessageType_MAX = Message_MessageType_DATA_REPLICATION_UNUSED;
constexpr int Message_MessageType_MessageType_ARRAYSIZE = Message_MessageType_MessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Message_MessageType_descriptor();
template<typename T>
inline const std::string& Message_MessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Message_MessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Message_MessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Message_MessageType_descriptor(), enum_t_value);
}
inline bool Message_MessageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Message_MessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Message_MessageType>(
    Message_MessageType_descriptor(), name, value);
}
// ===================================================================

class InformationalMessageContents_CollectionInformationRecord_CreationRateData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:InformationalMessageContents.CollectionInformationRecord.CreationRateData) */ {
 public:
  inline InformationalMessageContents_CollectionInformationRecord_CreationRateData() : InformationalMessageContents_CollectionInformationRecord_CreationRateData(nullptr) {}
  ~InformationalMessageContents_CollectionInformationRecord_CreationRateData() override;
  explicit constexpr InformationalMessageContents_CollectionInformationRecord_CreationRateData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InformationalMessageContents_CollectionInformationRecord_CreationRateData(const InformationalMessageContents_CollectionInformationRecord_CreationRateData& from);
  InformationalMessageContents_CollectionInformationRecord_CreationRateData(InformationalMessageContents_CollectionInformationRecord_CreationRateData&& from) noexcept
    : InformationalMessageContents_CollectionInformationRecord_CreationRateData() {
    *this = ::std::move(from);
  }

  inline InformationalMessageContents_CollectionInformationRecord_CreationRateData& operator=(const InformationalMessageContents_CollectionInformationRecord_CreationRateData& from) {
    CopyFrom(from);
    return *this;
  }
  inline InformationalMessageContents_CollectionInformationRecord_CreationRateData& operator=(InformationalMessageContents_CollectionInformationRecord_CreationRateData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InformationalMessageContents_CollectionInformationRecord_CreationRateData& default_instance() {
    return *internal_default_instance();
  }
  static inline const InformationalMessageContents_CollectionInformationRecord_CreationRateData* internal_default_instance() {
    return reinterpret_cast<const InformationalMessageContents_CollectionInformationRecord_CreationRateData*>(
               &_InformationalMessageContents_CollectionInformationRecord_CreationRateData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(InformationalMessageContents_CollectionInformationRecord_CreationRateData& a, InformationalMessageContents_CollectionInformationRecord_CreationRateData& b) {
    a.Swap(&b);
  }
  inline void Swap(InformationalMessageContents_CollectionInformationRecord_CreationRateData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InformationalMessageContents_CollectionInformationRecord_CreationRateData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InformationalMessageContents_CollectionInformationRecord_CreationRateData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InformationalMessageContents_CollectionInformationRecord_CreationRateData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InformationalMessageContents_CollectionInformationRecord_CreationRateData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const InformationalMessageContents_CollectionInformationRecord_CreationRateData& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InformationalMessageContents_CollectionInformationRecord_CreationRateData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "InformationalMessageContents.CollectionInformationRecord.CreationRateData";
  }
  protected:
  explicit InformationalMessageContents_CollectionInformationRecord_CreationRateData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kShortAllocationRatioFieldNumber = 1,
    kLongAllocationRatioFieldNumber = 2,
    kCreatedPreviousDayFieldNumber = 3,
    kCreatedPreviousWeekFieldNumber = 4,
    kKeyspaceIsEmptyFieldNumber = 5,
  };
  // double shortAllocationRatio = 1;
  void clear_shortallocationratio();
  double shortallocationratio() const;
  void set_shortallocationratio(double value);
  private:
  double _internal_shortallocationratio() const;
  void _internal_set_shortallocationratio(double value);
  public:

  // double longAllocationRatio = 2;
  void clear_longallocationratio();
  double longallocationratio() const;
  void set_longallocationratio(double value);
  private:
  double _internal_longallocationratio() const;
  void _internal_set_longallocationratio(double value);
  public:

  // double createdPreviousDay = 3;
  void clear_createdpreviousday();
  double createdpreviousday() const;
  void set_createdpreviousday(double value);
  private:
  double _internal_createdpreviousday() const;
  void _internal_set_createdpreviousday(double value);
  public:

  // double createdPreviousWeek = 4;
  void clear_createdpreviousweek();
  double createdpreviousweek() const;
  void set_createdpreviousweek(double value);
  private:
  double _internal_createdpreviousweek() const;
  void _internal_set_createdpreviousweek(double value);
  public:

  // bool keyspaceIsEmpty = 5;
  void clear_keyspaceisempty();
  bool keyspaceisempty() const;
  void set_keyspaceisempty(bool value);
  private:
  bool _internal_keyspaceisempty() const;
  void _internal_set_keyspaceisempty(bool value);
  public:

  // @@protoc_insertion_point(class_scope:InformationalMessageContents.CollectionInformationRecord.CreationRateData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double shortallocationratio_;
  double longallocationratio_;
  double createdpreviousday_;
  double createdpreviousweek_;
  bool keyspaceisempty_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class InformationalMessageContents_CollectionInformationRecord final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:InformationalMessageContents.CollectionInformationRecord) */ {
 public:
  inline InformationalMessageContents_CollectionInformationRecord() : InformationalMessageContents_CollectionInformationRecord(nullptr) {}
  ~InformationalMessageContents_CollectionInformationRecord() override;
  explicit constexpr InformationalMessageContents_CollectionInformationRecord(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InformationalMessageContents_CollectionInformationRecord(const InformationalMessageContents_CollectionInformationRecord& from);
  InformationalMessageContents_CollectionInformationRecord(InformationalMessageContents_CollectionInformationRecord&& from) noexcept
    : InformationalMessageContents_CollectionInformationRecord() {
    *this = ::std::move(from);
  }

  inline InformationalMessageContents_CollectionInformationRecord& operator=(const InformationalMessageContents_CollectionInformationRecord& from) {
    CopyFrom(from);
    return *this;
  }
  inline InformationalMessageContents_CollectionInformationRecord& operator=(InformationalMessageContents_CollectionInformationRecord&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InformationalMessageContents_CollectionInformationRecord& default_instance() {
    return *internal_default_instance();
  }
  static inline const InformationalMessageContents_CollectionInformationRecord* internal_default_instance() {
    return reinterpret_cast<const InformationalMessageContents_CollectionInformationRecord*>(
               &_InformationalMessageContents_CollectionInformationRecord_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(InformationalMessageContents_CollectionInformationRecord& a, InformationalMessageContents_CollectionInformationRecord& b) {
    a.Swap(&b);
  }
  inline void Swap(InformationalMessageContents_CollectionInformationRecord* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InformationalMessageContents_CollectionInformationRecord* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InformationalMessageContents_CollectionInformationRecord* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InformationalMessageContents_CollectionInformationRecord>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InformationalMessageContents_CollectionInformationRecord& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const InformationalMessageContents_CollectionInformationRecord& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InformationalMessageContents_CollectionInformationRecord* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "InformationalMessageContents.CollectionInformationRecord";
  }
  protected:
  explicit InformationalMessageContents_CollectionInformationRecord(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef InformationalMessageContents_CollectionInformationRecord_CreationRateData CreationRateData;

  // accessors -------------------------------------------------------

  enum : int {
    kCollectionNameFieldNumber = 1,
    kCreationRateDataFieldNumber = 2,
  };
  // string collectionName = 1;
  void clear_collectionname();
  const std::string& collectionname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_collectionname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_collectionname();
  PROTOBUF_NODISCARD std::string* release_collectionname();
  void set_allocated_collectionname(std::string* collectionname);
  private:
  const std::string& _internal_collectionname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_collectionname(const std::string& value);
  std::string* _internal_mutable_collectionname();
  public:

  // .InformationalMessageContents.CollectionInformationRecord.CreationRateData creationRateData = 2;
  bool has_creationratedata() const;
  private:
  bool _internal_has_creationratedata() const;
  public:
  void clear_creationratedata();
  const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData& creationratedata() const;
  PROTOBUF_NODISCARD ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* release_creationratedata();
  ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* mutable_creationratedata();
  void set_allocated_creationratedata(::InformationalMessageContents_CollectionInformationRecord_CreationRateData* creationratedata);
  private:
  const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData& _internal_creationratedata() const;
  ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* _internal_mutable_creationratedata();
  public:
  void unsafe_arena_set_allocated_creationratedata(
      ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* creationratedata);
  ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* unsafe_arena_release_creationratedata();

  // @@protoc_insertion_point(class_scope:InformationalMessageContents.CollectionInformationRecord)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr collectionname_;
  ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* creationratedata_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class InformationalMessageContents final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:InformationalMessageContents) */ {
 public:
  inline InformationalMessageContents() : InformationalMessageContents(nullptr) {}
  ~InformationalMessageContents() override;
  explicit constexpr InformationalMessageContents(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InformationalMessageContents(const InformationalMessageContents& from);
  InformationalMessageContents(InformationalMessageContents&& from) noexcept
    : InformationalMessageContents() {
    *this = ::std::move(from);
  }

  inline InformationalMessageContents& operator=(const InformationalMessageContents& from) {
    CopyFrom(from);
    return *this;
  }
  inline InformationalMessageContents& operator=(InformationalMessageContents&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InformationalMessageContents& default_instance() {
    return *internal_default_instance();
  }
  static inline const InformationalMessageContents* internal_default_instance() {
    return reinterpret_cast<const InformationalMessageContents*>(
               &_InformationalMessageContents_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(InformationalMessageContents& a, InformationalMessageContents& b) {
    a.Swap(&b);
  }
  inline void Swap(InformationalMessageContents* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InformationalMessageContents* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InformationalMessageContents* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InformationalMessageContents>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InformationalMessageContents& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const InformationalMessageContents& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InformationalMessageContents* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "InformationalMessageContents";
  }
  protected:
  explicit InformationalMessageContents(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef InformationalMessageContents_CollectionInformationRecord CollectionInformationRecord;

  // accessors -------------------------------------------------------

  enum : int {
    kRecordsFieldNumber = 1,
  };
  // repeated .InformationalMessageContents.CollectionInformationRecord records = 1;
  int records_size() const;
  private:
  int _internal_records_size() const;
  public:
  void clear_records();
  ::InformationalMessageContents_CollectionInformationRecord* mutable_records(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::InformationalMessageContents_CollectionInformationRecord >*
      mutable_records();
  private:
  const ::InformationalMessageContents_CollectionInformationRecord& _internal_records(int index) const;
  ::InformationalMessageContents_CollectionInformationRecord* _internal_add_records();
  public:
  const ::InformationalMessageContents_CollectionInformationRecord& records(int index) const;
  ::InformationalMessageContents_CollectionInformationRecord* add_records();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::InformationalMessageContents_CollectionInformationRecord >&
      records() const;

  // @@protoc_insertion_point(class_scope:InformationalMessageContents)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::InformationalMessageContents_CollectionInformationRecord > records_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class KeyspaceMessageContents_Keyspace final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:KeyspaceMessageContents.Keyspace) */ {
 public:
  inline KeyspaceMessageContents_Keyspace() : KeyspaceMessageContents_Keyspace(nullptr) {}
  ~KeyspaceMessageContents_Keyspace() override;
  explicit constexpr KeyspaceMessageContents_Keyspace(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  KeyspaceMessageContents_Keyspace(const KeyspaceMessageContents_Keyspace& from);
  KeyspaceMessageContents_Keyspace(KeyspaceMessageContents_Keyspace&& from) noexcept
    : KeyspaceMessageContents_Keyspace() {
    *this = ::std::move(from);
  }

  inline KeyspaceMessageContents_Keyspace& operator=(const KeyspaceMessageContents_Keyspace& from) {
    CopyFrom(from);
    return *this;
  }
  inline KeyspaceMessageContents_Keyspace& operator=(KeyspaceMessageContents_Keyspace&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const KeyspaceMessageContents_Keyspace& default_instance() {
    return *internal_default_instance();
  }
  static inline const KeyspaceMessageContents_Keyspace* internal_default_instance() {
    return reinterpret_cast<const KeyspaceMessageContents_Keyspace*>(
               &_KeyspaceMessageContents_Keyspace_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(KeyspaceMessageContents_Keyspace& a, KeyspaceMessageContents_Keyspace& b) {
    a.Swap(&b);
  }
  inline void Swap(KeyspaceMessageContents_Keyspace* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KeyspaceMessageContents_Keyspace* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  KeyspaceMessageContents_Keyspace* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<KeyspaceMessageContents_Keyspace>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const KeyspaceMessageContents_Keyspace& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const KeyspaceMessageContents_Keyspace& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KeyspaceMessageContents_Keyspace* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "KeyspaceMessageContents.Keyspace";
  }
  protected:
  explicit KeyspaceMessageContents_Keyspace(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kStartIDFieldNumber = 2,
    kEndIDFieldNumber = 3,
    kSuffixBitsFieldNumber = 4,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // uint64 startID = 2;
  void clear_startid();
  uint64_t startid() const;
  void set_startid(uint64_t value);
  private:
  uint64_t _internal_startid() const;
  void _internal_set_startid(uint64_t value);
  public:

  // uint64 endID = 3;
  void clear_endid();
  uint64_t endid() const;
  void set_endid(uint64_t value);
  private:
  uint64_t _internal_endid() const;
  void _internal_set_endid(uint64_t value);
  public:

  // uint32 suffixBits = 4;
  void clear_suffixbits();
  uint32_t suffixbits() const;
  void set_suffixbits(uint32_t value);
  private:
  uint32_t _internal_suffixbits() const;
  void _internal_set_suffixbits(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:KeyspaceMessageContents.Keyspace)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  uint64_t startid_;
  uint64_t endid_;
  uint32_t suffixbits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class KeyspaceMessageContents final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:KeyspaceMessageContents) */ {
 public:
  inline KeyspaceMessageContents() : KeyspaceMessageContents(nullptr) {}
  ~KeyspaceMessageContents() override;
  explicit constexpr KeyspaceMessageContents(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  KeyspaceMessageContents(const KeyspaceMessageContents& from);
  KeyspaceMessageContents(KeyspaceMessageContents&& from) noexcept
    : KeyspaceMessageContents() {
    *this = ::std::move(from);
  }

  inline KeyspaceMessageContents& operator=(const KeyspaceMessageContents& from) {
    CopyFrom(from);
    return *this;
  }
  inline KeyspaceMessageContents& operator=(KeyspaceMessageContents&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const KeyspaceMessageContents& default_instance() {
    return *internal_default_instance();
  }
  static inline const KeyspaceMessageContents* internal_default_instance() {
    return reinterpret_cast<const KeyspaceMessageContents*>(
               &_KeyspaceMessageContents_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(KeyspaceMessageContents& a, KeyspaceMessageContents& b) {
    a.Swap(&b);
  }
  inline void Swap(KeyspaceMessageContents* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KeyspaceMessageContents* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  KeyspaceMessageContents* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<KeyspaceMessageContents>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const KeyspaceMessageContents& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const KeyspaceMessageContents& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KeyspaceMessageContents* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "KeyspaceMessageContents";
  }
  protected:
  explicit KeyspaceMessageContents(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef KeyspaceMessageContents_Keyspace Keyspace;

  // accessors -------------------------------------------------------

  enum : int {
    kKeyspacesFieldNumber = 1,
  };
  // repeated .KeyspaceMessageContents.Keyspace keyspaces = 1;
  int keyspaces_size() const;
  private:
  int _internal_keyspaces_size() const;
  public:
  void clear_keyspaces();
  ::KeyspaceMessageContents_Keyspace* mutable_keyspaces(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::KeyspaceMessageContents_Keyspace >*
      mutable_keyspaces();
  private:
  const ::KeyspaceMessageContents_Keyspace& _internal_keyspaces(int index) const;
  ::KeyspaceMessageContents_Keyspace* _internal_add_keyspaces();
  public:
  const ::KeyspaceMessageContents_Keyspace& keyspaces(int index) const;
  ::KeyspaceMessageContents_Keyspace* add_keyspaces();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::KeyspaceMessageContents_Keyspace >&
      keyspaces() const;

  // @@protoc_insertion_point(class_scope:KeyspaceMessageContents)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::KeyspaceMessageContents_Keyspace > keyspaces_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class Message final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Message) */ {
 public:
  inline Message() : Message(nullptr) {}
  ~Message() override;
  explicit constexpr Message(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Message(const Message& from);
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Message& default_instance() {
    return *internal_default_instance();
  }
  enum MessageCase {
    kInfo = 8,
    kKeyspace = 9,
    MESSAGE_NOT_SET = 0,
  };

  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }
  inline void Swap(Message* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Message* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Message* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Message& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Message& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Message";
  }
  protected:
  explicit Message(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Message_ChannelState ChannelState;
  static constexpr ChannelState INITIAL_STARTUP =
    Message_ChannelState_INITIAL_STARTUP;
  static constexpr ChannelState NORMAL_COMMUNICATION =
    Message_ChannelState_NORMAL_COMMUNICATION;
  static constexpr ChannelState CHANNEL_SHUTDOWN =
    Message_ChannelState_CHANNEL_SHUTDOWN;
  static inline bool ChannelState_IsValid(int value) {
    return Message_ChannelState_IsValid(value);
  }
  static constexpr ChannelState ChannelState_MIN =
    Message_ChannelState_ChannelState_MIN;
  static constexpr ChannelState ChannelState_MAX =
    Message_ChannelState_ChannelState_MAX;
  static constexpr int ChannelState_ARRAYSIZE =
    Message_ChannelState_ChannelState_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  ChannelState_descriptor() {
    return Message_ChannelState_descriptor();
  }
  template<typename T>
  static inline const std::string& ChannelState_Name(T enum_t_value) {
    static_assert(::std::is_same<T, ChannelState>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function ChannelState_Name.");
    return Message_ChannelState_Name(enum_t_value);
  }
  static inline bool ChannelState_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      ChannelState* value) {
    return Message_ChannelState_Parse(name, value);
  }

  typedef Message_MessageType MessageType;
  static constexpr MessageType INFORMATION =
    Message_MessageType_INFORMATION;
  static constexpr MessageType KEYSPACE =
    Message_MessageType_KEYSPACE;
  static constexpr MessageType DATA_REPLICATION_UNUSED =
    Message_MessageType_DATA_REPLICATION_UNUSED;
  static inline bool MessageType_IsValid(int value) {
    return Message_MessageType_IsValid(value);
  }
  static constexpr MessageType MessageType_MIN =
    Message_MessageType_MessageType_MIN;
  static constexpr MessageType MessageType_MAX =
    Message_MessageType_MessageType_MAX;
  static constexpr int MessageType_ARRAYSIZE =
    Message_MessageType_MessageType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  MessageType_descriptor() {
    return Message_MessageType_descriptor();
  }
  template<typename T>
  static inline const std::string& MessageType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MessageType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MessageType_Name.");
    return Message_MessageType_Name(enum_t_value);
  }
  static inline bool MessageType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      MessageType* value) {
    return Message_MessageType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSourceNodeIDFieldNumber = 1,
    kDestNodeIDFieldNumber = 2,
    kTimestampFieldNumber = 5,
    kLastReceivedMsgFieldNumber = 3,
    kChannelStateFieldNumber = 4,
    kMessageTypeFieldNumber = 7,
    kMessageIDFieldNumber = 6,
    kInfoFieldNumber = 8,
    kKeyspaceFieldNumber = 9,
  };
  // bytes sourceNodeID = 1;
  void clear_sourcenodeid();
  const std::string& sourcenodeid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sourcenodeid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sourcenodeid();
  PROTOBUF_NODISCARD std::string* release_sourcenodeid();
  void set_allocated_sourcenodeid(std::string* sourcenodeid);
  private:
  const std::string& _internal_sourcenodeid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sourcenodeid(const std::string& value);
  std::string* _internal_mutable_sourcenodeid();
  public:

  // bytes destNodeID = 2;
  void clear_destnodeid();
  const std::string& destnodeid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_destnodeid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_destnodeid();
  PROTOBUF_NODISCARD std::string* release_destnodeid();
  void set_allocated_destnodeid(std::string* destnodeid);
  private:
  const std::string& _internal_destnodeid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_destnodeid(const std::string& value);
  std::string* _internal_mutable_destnodeid();
  public:

  // .google.protobuf.Timestamp timestamp = 5;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // uint64 lastReceivedMsg = 3;
  void clear_lastreceivedmsg();
  uint64_t lastreceivedmsg() const;
  void set_lastreceivedmsg(uint64_t value);
  private:
  uint64_t _internal_lastreceivedmsg() const;
  void _internal_set_lastreceivedmsg(uint64_t value);
  public:

  // .Message.ChannelState channelState = 4;
  void clear_channelstate();
  ::Message_ChannelState channelstate() const;
  void set_channelstate(::Message_ChannelState value);
  private:
  ::Message_ChannelState _internal_channelstate() const;
  void _internal_set_channelstate(::Message_ChannelState value);
  public:

  // .Message.MessageType messageType = 7;
  void clear_messagetype();
  ::Message_MessageType messagetype() const;
  void set_messagetype(::Message_MessageType value);
  private:
  ::Message_MessageType _internal_messagetype() const;
  void _internal_set_messagetype(::Message_MessageType value);
  public:

  // sint64 messageID = 6;
  void clear_messageid();
  int64_t messageid() const;
  void set_messageid(int64_t value);
  private:
  int64_t _internal_messageid() const;
  void _internal_set_messageid(int64_t value);
  public:

  // .InformationalMessageContents info = 8;
  bool has_info() const;
  private:
  bool _internal_has_info() const;
  public:
  void clear_info();
  const ::InformationalMessageContents& info() const;
  PROTOBUF_NODISCARD ::InformationalMessageContents* release_info();
  ::InformationalMessageContents* mutable_info();
  void set_allocated_info(::InformationalMessageContents* info);
  private:
  const ::InformationalMessageContents& _internal_info() const;
  ::InformationalMessageContents* _internal_mutable_info();
  public:
  void unsafe_arena_set_allocated_info(
      ::InformationalMessageContents* info);
  ::InformationalMessageContents* unsafe_arena_release_info();

  // .KeyspaceMessageContents keyspace = 9;
  bool has_keyspace() const;
  private:
  bool _internal_has_keyspace() const;
  public:
  void clear_keyspace();
  const ::KeyspaceMessageContents& keyspace() const;
  PROTOBUF_NODISCARD ::KeyspaceMessageContents* release_keyspace();
  ::KeyspaceMessageContents* mutable_keyspace();
  void set_allocated_keyspace(::KeyspaceMessageContents* keyspace);
  private:
  const ::KeyspaceMessageContents& _internal_keyspace() const;
  ::KeyspaceMessageContents* _internal_mutable_keyspace();
  public:
  void unsafe_arena_set_allocated_keyspace(
      ::KeyspaceMessageContents* keyspace);
  ::KeyspaceMessageContents* unsafe_arena_release_keyspace();

  void clear_message();
  MessageCase message_case() const;
  // @@protoc_insertion_point(class_scope:Message)
 private:
  class _Internal;
  void set_has_info();
  void set_has_keyspace();

  inline bool has_message() const;
  inline void clear_has_message();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sourcenodeid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr destnodeid_;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  uint64_t lastreceivedmsg_;
  int channelstate_;
  int messagetype_;
  int64_t messageid_;
  union MessageUnion {
    constexpr MessageUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
    ::InformationalMessageContents* info_;
    ::KeyspaceMessageContents* keyspace_;
  } message_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  uint32_t _oneof_case_[1];

  friend struct ::TableStruct_message_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InformationalMessageContents_CollectionInformationRecord_CreationRateData

// double shortAllocationRatio = 1;
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::clear_shortallocationratio() {
  shortallocationratio_ = 0;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_shortallocationratio() const {
  return shortallocationratio_;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::shortallocationratio() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.CreationRateData.shortAllocationRatio)
  return _internal_shortallocationratio();
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_set_shortallocationratio(double value) {
  
  shortallocationratio_ = value;
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::set_shortallocationratio(double value) {
  _internal_set_shortallocationratio(value);
  // @@protoc_insertion_point(field_set:InformationalMessageContents.CollectionInformationRecord.CreationRateData.shortAllocationRatio)
}

// double longAllocationRatio = 2;
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::clear_longallocationratio() {
  longallocationratio_ = 0;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_longallocationratio() const {
  return longallocationratio_;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::longallocationratio() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.CreationRateData.longAllocationRatio)
  return _internal_longallocationratio();
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_set_longallocationratio(double value) {
  
  longallocationratio_ = value;
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::set_longallocationratio(double value) {
  _internal_set_longallocationratio(value);
  // @@protoc_insertion_point(field_set:InformationalMessageContents.CollectionInformationRecord.CreationRateData.longAllocationRatio)
}

// double createdPreviousDay = 3;
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::clear_createdpreviousday() {
  createdpreviousday_ = 0;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_createdpreviousday() const {
  return createdpreviousday_;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::createdpreviousday() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.CreationRateData.createdPreviousDay)
  return _internal_createdpreviousday();
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_set_createdpreviousday(double value) {
  
  createdpreviousday_ = value;
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::set_createdpreviousday(double value) {
  _internal_set_createdpreviousday(value);
  // @@protoc_insertion_point(field_set:InformationalMessageContents.CollectionInformationRecord.CreationRateData.createdPreviousDay)
}

// double createdPreviousWeek = 4;
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::clear_createdpreviousweek() {
  createdpreviousweek_ = 0;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_createdpreviousweek() const {
  return createdpreviousweek_;
}
inline double InformationalMessageContents_CollectionInformationRecord_CreationRateData::createdpreviousweek() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.CreationRateData.createdPreviousWeek)
  return _internal_createdpreviousweek();
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_set_createdpreviousweek(double value) {
  
  createdpreviousweek_ = value;
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::set_createdpreviousweek(double value) {
  _internal_set_createdpreviousweek(value);
  // @@protoc_insertion_point(field_set:InformationalMessageContents.CollectionInformationRecord.CreationRateData.createdPreviousWeek)
}

// bool keyspaceIsEmpty = 5;
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::clear_keyspaceisempty() {
  keyspaceisempty_ = false;
}
inline bool InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_keyspaceisempty() const {
  return keyspaceisempty_;
}
inline bool InformationalMessageContents_CollectionInformationRecord_CreationRateData::keyspaceisempty() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.CreationRateData.keyspaceIsEmpty)
  return _internal_keyspaceisempty();
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::_internal_set_keyspaceisempty(bool value) {
  
  keyspaceisempty_ = value;
}
inline void InformationalMessageContents_CollectionInformationRecord_CreationRateData::set_keyspaceisempty(bool value) {
  _internal_set_keyspaceisempty(value);
  // @@protoc_insertion_point(field_set:InformationalMessageContents.CollectionInformationRecord.CreationRateData.keyspaceIsEmpty)
}

// -------------------------------------------------------------------

// InformationalMessageContents_CollectionInformationRecord

// string collectionName = 1;
inline void InformationalMessageContents_CollectionInformationRecord::clear_collectionname() {
  collectionname_.ClearToEmpty();
}
inline const std::string& InformationalMessageContents_CollectionInformationRecord::collectionname() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.collectionName)
  return _internal_collectionname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void InformationalMessageContents_CollectionInformationRecord::set_collectionname(ArgT0&& arg0, ArgT... args) {
 
 collectionname_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:InformationalMessageContents.CollectionInformationRecord.collectionName)
}
inline std::string* InformationalMessageContents_CollectionInformationRecord::mutable_collectionname() {
  std::string* _s = _internal_mutable_collectionname();
  // @@protoc_insertion_point(field_mutable:InformationalMessageContents.CollectionInformationRecord.collectionName)
  return _s;
}
inline const std::string& InformationalMessageContents_CollectionInformationRecord::_internal_collectionname() const {
  return collectionname_.Get();
}
inline void InformationalMessageContents_CollectionInformationRecord::_internal_set_collectionname(const std::string& value) {
  
  collectionname_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* InformationalMessageContents_CollectionInformationRecord::_internal_mutable_collectionname() {
  
  return collectionname_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* InformationalMessageContents_CollectionInformationRecord::release_collectionname() {
  // @@protoc_insertion_point(field_release:InformationalMessageContents.CollectionInformationRecord.collectionName)
  return collectionname_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void InformationalMessageContents_CollectionInformationRecord::set_allocated_collectionname(std::string* collectionname) {
  if (collectionname != nullptr) {
    
  } else {
    
  }
  collectionname_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), collectionname,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (collectionname_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    collectionname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:InformationalMessageContents.CollectionInformationRecord.collectionName)
}

// .InformationalMessageContents.CollectionInformationRecord.CreationRateData creationRateData = 2;
inline bool InformationalMessageContents_CollectionInformationRecord::_internal_has_creationratedata() const {
  return this != internal_default_instance() && creationratedata_ != nullptr;
}
inline bool InformationalMessageContents_CollectionInformationRecord::has_creationratedata() const {
  return _internal_has_creationratedata();
}
inline void InformationalMessageContents_CollectionInformationRecord::clear_creationratedata() {
  if (GetArenaForAllocation() == nullptr && creationratedata_ != nullptr) {
    delete creationratedata_;
  }
  creationratedata_ = nullptr;
}
inline const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData& InformationalMessageContents_CollectionInformationRecord::_internal_creationratedata() const {
  const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* p = creationratedata_;
  return p != nullptr ? *p : reinterpret_cast<const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData&>(
      ::_InformationalMessageContents_CollectionInformationRecord_CreationRateData_default_instance_);
}
inline const ::InformationalMessageContents_CollectionInformationRecord_CreationRateData& InformationalMessageContents_CollectionInformationRecord::creationratedata() const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.CollectionInformationRecord.creationRateData)
  return _internal_creationratedata();
}
inline void InformationalMessageContents_CollectionInformationRecord::unsafe_arena_set_allocated_creationratedata(
    ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* creationratedata) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(creationratedata_);
  }
  creationratedata_ = creationratedata;
  if (creationratedata) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:InformationalMessageContents.CollectionInformationRecord.creationRateData)
}
inline ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* InformationalMessageContents_CollectionInformationRecord::release_creationratedata() {
  
  ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* temp = creationratedata_;
  creationratedata_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* InformationalMessageContents_CollectionInformationRecord::unsafe_arena_release_creationratedata() {
  // @@protoc_insertion_point(field_release:InformationalMessageContents.CollectionInformationRecord.creationRateData)
  
  ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* temp = creationratedata_;
  creationratedata_ = nullptr;
  return temp;
}
inline ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* InformationalMessageContents_CollectionInformationRecord::_internal_mutable_creationratedata() {
  
  if (creationratedata_ == nullptr) {
    auto* p = CreateMaybeMessage<::InformationalMessageContents_CollectionInformationRecord_CreationRateData>(GetArenaForAllocation());
    creationratedata_ = p;
  }
  return creationratedata_;
}
inline ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* InformationalMessageContents_CollectionInformationRecord::mutable_creationratedata() {
  ::InformationalMessageContents_CollectionInformationRecord_CreationRateData* _msg = _internal_mutable_creationratedata();
  // @@protoc_insertion_point(field_mutable:InformationalMessageContents.CollectionInformationRecord.creationRateData)
  return _msg;
}
inline void InformationalMessageContents_CollectionInformationRecord::set_allocated_creationratedata(::InformationalMessageContents_CollectionInformationRecord_CreationRateData* creationratedata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete creationratedata_;
  }
  if (creationratedata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::InformationalMessageContents_CollectionInformationRecord_CreationRateData>::GetOwningArena(creationratedata);
    if (message_arena != submessage_arena) {
      creationratedata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, creationratedata, submessage_arena);
    }
    
  } else {
    
  }
  creationratedata_ = creationratedata;
  // @@protoc_insertion_point(field_set_allocated:InformationalMessageContents.CollectionInformationRecord.creationRateData)
}

// -------------------------------------------------------------------

// InformationalMessageContents

// repeated .InformationalMessageContents.CollectionInformationRecord records = 1;
inline int InformationalMessageContents::_internal_records_size() const {
  return records_.size();
}
inline int InformationalMessageContents::records_size() const {
  return _internal_records_size();
}
inline void InformationalMessageContents::clear_records() {
  records_.Clear();
}
inline ::InformationalMessageContents_CollectionInformationRecord* InformationalMessageContents::mutable_records(int index) {
  // @@protoc_insertion_point(field_mutable:InformationalMessageContents.records)
  return records_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::InformationalMessageContents_CollectionInformationRecord >*
InformationalMessageContents::mutable_records() {
  // @@protoc_insertion_point(field_mutable_list:InformationalMessageContents.records)
  return &records_;
}
inline const ::InformationalMessageContents_CollectionInformationRecord& InformationalMessageContents::_internal_records(int index) const {
  return records_.Get(index);
}
inline const ::InformationalMessageContents_CollectionInformationRecord& InformationalMessageContents::records(int index) const {
  // @@protoc_insertion_point(field_get:InformationalMessageContents.records)
  return _internal_records(index);
}
inline ::InformationalMessageContents_CollectionInformationRecord* InformationalMessageContents::_internal_add_records() {
  return records_.Add();
}
inline ::InformationalMessageContents_CollectionInformationRecord* InformationalMessageContents::add_records() {
  ::InformationalMessageContents_CollectionInformationRecord* _add = _internal_add_records();
  // @@protoc_insertion_point(field_add:InformationalMessageContents.records)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::InformationalMessageContents_CollectionInformationRecord >&
InformationalMessageContents::records() const {
  // @@protoc_insertion_point(field_list:InformationalMessageContents.records)
  return records_;
}

// -------------------------------------------------------------------

// KeyspaceMessageContents_Keyspace

// string name = 1;
inline void KeyspaceMessageContents_Keyspace::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& KeyspaceMessageContents_Keyspace::name() const {
  // @@protoc_insertion_point(field_get:KeyspaceMessageContents.Keyspace.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void KeyspaceMessageContents_Keyspace::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:KeyspaceMessageContents.Keyspace.name)
}
inline std::string* KeyspaceMessageContents_Keyspace::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:KeyspaceMessageContents.Keyspace.name)
  return _s;
}
inline const std::string& KeyspaceMessageContents_Keyspace::_internal_name() const {
  return name_.Get();
}
inline void KeyspaceMessageContents_Keyspace::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* KeyspaceMessageContents_Keyspace::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* KeyspaceMessageContents_Keyspace::release_name() {
  // @@protoc_insertion_point(field_release:KeyspaceMessageContents.Keyspace.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void KeyspaceMessageContents_Keyspace::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:KeyspaceMessageContents.Keyspace.name)
}

// uint64 startID = 2;
inline void KeyspaceMessageContents_Keyspace::clear_startid() {
  startid_ = uint64_t{0u};
}
inline uint64_t KeyspaceMessageContents_Keyspace::_internal_startid() const {
  return startid_;
}
inline uint64_t KeyspaceMessageContents_Keyspace::startid() const {
  // @@protoc_insertion_point(field_get:KeyspaceMessageContents.Keyspace.startID)
  return _internal_startid();
}
inline void KeyspaceMessageContents_Keyspace::_internal_set_startid(uint64_t value) {
  
  startid_ = value;
}
inline void KeyspaceMessageContents_Keyspace::set_startid(uint64_t value) {
  _internal_set_startid(value);
  // @@protoc_insertion_point(field_set:KeyspaceMessageContents.Keyspace.startID)
}

// uint64 endID = 3;
inline void KeyspaceMessageContents_Keyspace::clear_endid() {
  endid_ = uint64_t{0u};
}
inline uint64_t KeyspaceMessageContents_Keyspace::_internal_endid() const {
  return endid_;
}
inline uint64_t KeyspaceMessageContents_Keyspace::endid() const {
  // @@protoc_insertion_point(field_get:KeyspaceMessageContents.Keyspace.endID)
  return _internal_endid();
}
inline void KeyspaceMessageContents_Keyspace::_internal_set_endid(uint64_t value) {
  
  endid_ = value;
}
inline void KeyspaceMessageContents_Keyspace::set_endid(uint64_t value) {
  _internal_set_endid(value);
  // @@protoc_insertion_point(field_set:KeyspaceMessageContents.Keyspace.endID)
}

// uint32 suffixBits = 4;
inline void KeyspaceMessageContents_Keyspace::clear_suffixbits() {
  suffixbits_ = 0u;
}
inline uint32_t KeyspaceMessageContents_Keyspace::_internal_suffixbits() const {
  return suffixbits_;
}
inline uint32_t KeyspaceMessageContents_Keyspace::suffixbits() const {
  // @@protoc_insertion_point(field_get:KeyspaceMessageContents.Keyspace.suffixBits)
  return _internal_suffixbits();
}
inline void KeyspaceMessageContents_Keyspace::_internal_set_suffixbits(uint32_t value) {
  
  suffixbits_ = value;
}
inline void KeyspaceMessageContents_Keyspace::set_suffixbits(uint32_t value) {
  _internal_set_suffixbits(value);
  // @@protoc_insertion_point(field_set:KeyspaceMessageContents.Keyspace.suffixBits)
}

// -------------------------------------------------------------------

// KeyspaceMessageContents

// repeated .KeyspaceMessageContents.Keyspace keyspaces = 1;
inline int KeyspaceMessageContents::_internal_keyspaces_size() const {
  return keyspaces_.size();
}
inline int KeyspaceMessageContents::keyspaces_size() const {
  return _internal_keyspaces_size();
}
inline void KeyspaceMessageContents::clear_keyspaces() {
  keyspaces_.Clear();
}
inline ::KeyspaceMessageContents_Keyspace* KeyspaceMessageContents::mutable_keyspaces(int index) {
  // @@protoc_insertion_point(field_mutable:KeyspaceMessageContents.keyspaces)
  return keyspaces_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::KeyspaceMessageContents_Keyspace >*
KeyspaceMessageContents::mutable_keyspaces() {
  // @@protoc_insertion_point(field_mutable_list:KeyspaceMessageContents.keyspaces)
  return &keyspaces_;
}
inline const ::KeyspaceMessageContents_Keyspace& KeyspaceMessageContents::_internal_keyspaces(int index) const {
  return keyspaces_.Get(index);
}
inline const ::KeyspaceMessageContents_Keyspace& KeyspaceMessageContents::keyspaces(int index) const {
  // @@protoc_insertion_point(field_get:KeyspaceMessageContents.keyspaces)
  return _internal_keyspaces(index);
}
inline ::KeyspaceMessageContents_Keyspace* KeyspaceMessageContents::_internal_add_keyspaces() {
  return keyspaces_.Add();
}
inline ::KeyspaceMessageContents_Keyspace* KeyspaceMessageContents::add_keyspaces() {
  ::KeyspaceMessageContents_Keyspace* _add = _internal_add_keyspaces();
  // @@protoc_insertion_point(field_add:KeyspaceMessageContents.keyspaces)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::KeyspaceMessageContents_Keyspace >&
KeyspaceMessageContents::keyspaces() const {
  // @@protoc_insertion_point(field_list:KeyspaceMessageContents.keyspaces)
  return keyspaces_;
}

// -------------------------------------------------------------------

// Message

// bytes sourceNodeID = 1;
inline void Message::clear_sourcenodeid() {
  sourcenodeid_.ClearToEmpty();
}
inline const std::string& Message::sourcenodeid() const {
  // @@protoc_insertion_point(field_get:Message.sourceNodeID)
  return _internal_sourcenodeid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Message::set_sourcenodeid(ArgT0&& arg0, ArgT... args) {
 
 sourcenodeid_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Message.sourceNodeID)
}
inline std::string* Message::mutable_sourcenodeid() {
  std::string* _s = _internal_mutable_sourcenodeid();
  // @@protoc_insertion_point(field_mutable:Message.sourceNodeID)
  return _s;
}
inline const std::string& Message::_internal_sourcenodeid() const {
  return sourcenodeid_.Get();
}
inline void Message::_internal_set_sourcenodeid(const std::string& value) {
  
  sourcenodeid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Message::_internal_mutable_sourcenodeid() {
  
  return sourcenodeid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Message::release_sourcenodeid() {
  // @@protoc_insertion_point(field_release:Message.sourceNodeID)
  return sourcenodeid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Message::set_allocated_sourcenodeid(std::string* sourcenodeid) {
  if (sourcenodeid != nullptr) {
    
  } else {
    
  }
  sourcenodeid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sourcenodeid,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (sourcenodeid_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    sourcenodeid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Message.sourceNodeID)
}

// bytes destNodeID = 2;
inline void Message::clear_destnodeid() {
  destnodeid_.ClearToEmpty();
}
inline const std::string& Message::destnodeid() const {
  // @@protoc_insertion_point(field_get:Message.destNodeID)
  return _internal_destnodeid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Message::set_destnodeid(ArgT0&& arg0, ArgT... args) {
 
 destnodeid_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Message.destNodeID)
}
inline std::string* Message::mutable_destnodeid() {
  std::string* _s = _internal_mutable_destnodeid();
  // @@protoc_insertion_point(field_mutable:Message.destNodeID)
  return _s;
}
inline const std::string& Message::_internal_destnodeid() const {
  return destnodeid_.Get();
}
inline void Message::_internal_set_destnodeid(const std::string& value) {
  
  destnodeid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Message::_internal_mutable_destnodeid() {
  
  return destnodeid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Message::release_destnodeid() {
  // @@protoc_insertion_point(field_release:Message.destNodeID)
  return destnodeid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Message::set_allocated_destnodeid(std::string* destnodeid) {
  if (destnodeid != nullptr) {
    
  } else {
    
  }
  destnodeid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), destnodeid,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (destnodeid_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    destnodeid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Message.destNodeID)
}

// uint64 lastReceivedMsg = 3;
inline void Message::clear_lastreceivedmsg() {
  lastreceivedmsg_ = uint64_t{0u};
}
inline uint64_t Message::_internal_lastreceivedmsg() const {
  return lastreceivedmsg_;
}
inline uint64_t Message::lastreceivedmsg() const {
  // @@protoc_insertion_point(field_get:Message.lastReceivedMsg)
  return _internal_lastreceivedmsg();
}
inline void Message::_internal_set_lastreceivedmsg(uint64_t value) {
  
  lastreceivedmsg_ = value;
}
inline void Message::set_lastreceivedmsg(uint64_t value) {
  _internal_set_lastreceivedmsg(value);
  // @@protoc_insertion_point(field_set:Message.lastReceivedMsg)
}

// .Message.ChannelState channelState = 4;
inline void Message::clear_channelstate() {
  channelstate_ = 0;
}
inline ::Message_ChannelState Message::_internal_channelstate() const {
  return static_cast< ::Message_ChannelState >(channelstate_);
}
inline ::Message_ChannelState Message::channelstate() const {
  // @@protoc_insertion_point(field_get:Message.channelState)
  return _internal_channelstate();
}
inline void Message::_internal_set_channelstate(::Message_ChannelState value) {
  
  channelstate_ = value;
}
inline void Message::set_channelstate(::Message_ChannelState value) {
  _internal_set_channelstate(value);
  // @@protoc_insertion_point(field_set:Message.channelState)
}

// .google.protobuf.Timestamp timestamp = 5;
inline bool Message::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool Message::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& Message::_internal_timestamp() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& Message::timestamp() const {
  // @@protoc_insertion_point(field_get:Message.timestamp)
  return _internal_timestamp();
}
inline void Message::unsafe_arena_set_allocated_timestamp(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Message.timestamp)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Message::release_timestamp() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Message::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:Message.timestamp)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Message::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    timestamp_ = p;
  }
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Message::mutable_timestamp() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:Message.timestamp)
  return _msg;
}
inline void Message::set_allocated_timestamp(::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp));
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:Message.timestamp)
}

// sint64 messageID = 6;
inline void Message::clear_messageid() {
  messageid_ = int64_t{0};
}
inline int64_t Message::_internal_messageid() const {
  return messageid_;
}
inline int64_t Message::messageid() const {
  // @@protoc_insertion_point(field_get:Message.messageID)
  return _internal_messageid();
}
inline void Message::_internal_set_messageid(int64_t value) {
  
  messageid_ = value;
}
inline void Message::set_messageid(int64_t value) {
  _internal_set_messageid(value);
  // @@protoc_insertion_point(field_set:Message.messageID)
}

// .Message.MessageType messageType = 7;
inline void Message::clear_messagetype() {
  messagetype_ = 0;
}
inline ::Message_MessageType Message::_internal_messagetype() const {
  return static_cast< ::Message_MessageType >(messagetype_);
}
inline ::Message_MessageType Message::messagetype() const {
  // @@protoc_insertion_point(field_get:Message.messageType)
  return _internal_messagetype();
}
inline void Message::_internal_set_messagetype(::Message_MessageType value) {
  
  messagetype_ = value;
}
inline void Message::set_messagetype(::Message_MessageType value) {
  _internal_set_messagetype(value);
  // @@protoc_insertion_point(field_set:Message.messageType)
}

// .InformationalMessageContents info = 8;
inline bool Message::_internal_has_info() const {
  return message_case() == kInfo;
}
inline bool Message::has_info() const {
  return _internal_has_info();
}
inline void Message::set_has_info() {
  _oneof_case_[0] = kInfo;
}
inline void Message::clear_info() {
  if (_internal_has_info()) {
    if (GetArenaForAllocation() == nullptr) {
      delete message_.info_;
    }
    clear_has_message();
  }
}
inline ::InformationalMessageContents* Message::release_info() {
  // @@protoc_insertion_point(field_release:Message.info)
  if (_internal_has_info()) {
    clear_has_message();
      ::InformationalMessageContents* temp = message_.info_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    message_.info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::InformationalMessageContents& Message::_internal_info() const {
  return _internal_has_info()
      ? *message_.info_
      : reinterpret_cast< ::InformationalMessageContents&>(::_InformationalMessageContents_default_instance_);
}
inline const ::InformationalMessageContents& Message::info() const {
  // @@protoc_insertion_point(field_get:Message.info)
  return _internal_info();
}
inline ::InformationalMessageContents* Message::unsafe_arena_release_info() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Message.info)
  if (_internal_has_info()) {
    clear_has_message();
    ::InformationalMessageContents* temp = message_.info_;
    message_.info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Message::unsafe_arena_set_allocated_info(::InformationalMessageContents* info) {
  clear_message();
  if (info) {
    set_has_info();
    message_.info_ = info;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Message.info)
}
inline ::InformationalMessageContents* Message::_internal_mutable_info() {
  if (!_internal_has_info()) {
    clear_message();
    set_has_info();
    message_.info_ = CreateMaybeMessage< ::InformationalMessageContents >(GetArenaForAllocation());
  }
  return message_.info_;
}
inline ::InformationalMessageContents* Message::mutable_info() {
  ::InformationalMessageContents* _msg = _internal_mutable_info();
  // @@protoc_insertion_point(field_mutable:Message.info)
  return _msg;
}

// .KeyspaceMessageContents keyspace = 9;
inline bool Message::_internal_has_keyspace() const {
  return message_case() == kKeyspace;
}
inline bool Message::has_keyspace() const {
  return _internal_has_keyspace();
}
inline void Message::set_has_keyspace() {
  _oneof_case_[0] = kKeyspace;
}
inline void Message::clear_keyspace() {
  if (_internal_has_keyspace()) {
    if (GetArenaForAllocation() == nullptr) {
      delete message_.keyspace_;
    }
    clear_has_message();
  }
}
inline ::KeyspaceMessageContents* Message::release_keyspace() {
  // @@protoc_insertion_point(field_release:Message.keyspace)
  if (_internal_has_keyspace()) {
    clear_has_message();
      ::KeyspaceMessageContents* temp = message_.keyspace_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    message_.keyspace_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::KeyspaceMessageContents& Message::_internal_keyspace() const {
  return _internal_has_keyspace()
      ? *message_.keyspace_
      : reinterpret_cast< ::KeyspaceMessageContents&>(::_KeyspaceMessageContents_default_instance_);
}
inline const ::KeyspaceMessageContents& Message::keyspace() const {
  // @@protoc_insertion_point(field_get:Message.keyspace)
  return _internal_keyspace();
}
inline ::KeyspaceMessageContents* Message::unsafe_arena_release_keyspace() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Message.keyspace)
  if (_internal_has_keyspace()) {
    clear_has_message();
    ::KeyspaceMessageContents* temp = message_.keyspace_;
    message_.keyspace_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Message::unsafe_arena_set_allocated_keyspace(::KeyspaceMessageContents* keyspace) {
  clear_message();
  if (keyspace) {
    set_has_keyspace();
    message_.keyspace_ = keyspace;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Message.keyspace)
}
inline ::KeyspaceMessageContents* Message::_internal_mutable_keyspace() {
  if (!_internal_has_keyspace()) {
    clear_message();
    set_has_keyspace();
    message_.keyspace_ = CreateMaybeMessage< ::KeyspaceMessageContents >(GetArenaForAllocation());
  }
  return message_.keyspace_;
}
inline ::KeyspaceMessageContents* Message::mutable_keyspace() {
  ::KeyspaceMessageContents* _msg = _internal_mutable_keyspace();
  // @@protoc_insertion_point(field_mutable:Message.keyspace)
  return _msg;
}

inline bool Message::has_message() const {
  return message_case() != MESSAGE_NOT_SET;
}
inline void Message::clear_has_message() {
  _oneof_case_[0] = MESSAGE_NOT_SET;
}
inline Message::MessageCase Message::message_case() const {
  return Message::MessageCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Message_ChannelState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Message_ChannelState>() {
  return ::Message_ChannelState_descriptor();
}
template <> struct is_proto_enum< ::Message_MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Message_MessageType>() {
  return ::Message_MessageType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_2eproto
