name: build-and-test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install abseil library
        run: sudo apt-get install abseil
      - name: Install protobuf library
        run: sudo apt-get install protobuf
      - name: Build and test ADAK
        run: make all build-and-test USE_CORES=1
      - uses: actions/upload-artifact@v2
        with:
          name: outputs
          path: build/src/outputs/
