name: build-and-test
on: [push]
jobs:
  build:
    # Build and cache protobuf from https://lukasjoswiak.com/github-actions-protobuf/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache protobuf library
        id: cache-protobuf
        uses: actions/cache@v1
        with:
          path: protobuf
          key: ${{ runner.os }}-protobuf
      - name: Build protobuf library
        if: steps.cache-protobuf.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/protocolbuffers/protobuf.git
          cd protobuf
          git checkout 13b3647 # restore autotools version because I haven't figured out bazel build yet
          git submodule update --init --recursive
          ./autogen.sh
          ./autogen.sh  # run autogen twice due to alleged bug
          ./configure
          make
          make check
      - name: Install protobuf library
        if: always()
        run: |
          cd protobuf
          sudo make install
          sudo ldconfig
      # We may not need abseil because we're using such an old commit of protobuf
      #- name: Build and install Abseil
      #  run: |
      #    git clone https://github.com/abseil/abseil-cpp
      #    cd abseil-cpp && mkdir build && cd build && cmake -DCMAKE_CXX_STANDARD=14 .. && sudo make install
  test-group-1:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build and test ADAK group 1
        if: always()
        run: |
          ls
          make build-and-test-1-of-2 USE_CORES=1
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: outputs
          path: build/src/outputs/
  test-group-2:
    runs-on: ubuntu-latest
    needs: [ build, test-group-1 ]
    steps:
      - name: Build and test ADAK group 2
        if: always()
        run: make build-and-test-2-of-2 USE_CORES=1
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: outputs
          path: build/src/outputs/
