name: build-and-test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache protobuf library
        id: cache-protobuf
        uses: actions/cache@v1
        with:
          path: protobuf
          key: ${{ runner.os }}-protobuf
      - name: Build protobuf library
        if: steps.cache-protobuf.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/protocolbuffers/protobuf.git
          cd protobuf
          git submodule update --init --recursive
          ./autogen.sh
          ./autogen.sh  # run autogen twice due to alleged bug
          ./configure
          make
          make check
      - name: Install protobuf library
        run: |
          cd protobuf
          sudo make install
          sudo ldconfig
      - name: make
        run: make all USE_CORES=1
      - name: test
        run: make run-repeatable sanitize
          make run-repeatable sanitize
          make compare
      - name: Save outputs
        uses: actions/upload-artifact@v2
        with:
          name: outputs
          path: build/src/outputs/
