name: build-and-test
on: [push, workflow_dispatch]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and install Google Test
        if: always()
        run: make gtest install-gtest
      - name: Build and install Abseil
        if: always()
        run: make abseil install-abseil
      - name: Cache protobuf library
        id: cache-protobuf
        uses: actions/cache@v1
        with:
          path: protobuf
          key: ${{ runner.os }}-protobuf
      - name: Build Protobuf
        if: always()
        run: make protobuf
      - name: Install protobuf library
        if: always()
        run: make install-protobuf
      - name: Build and test ADAK
        if: always()
        run: make build-and-test USE_CORES=1
      - uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: build/src/outputs/
